### PR TITLE
Unset Qt High-DPI scaling policy

### LINKED ISSUE #331: weird scaling on windows on latest devbuilds
### Operating System

Windows

### Description of bug

weird scaling

### Steps to reproduce

open polymc and see

immagine

this is how it looked like before: 
immagine

### Suspected cause

#315 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### PR DESCRIPTION
**Pull request by DioEgizio**
Closes #331 

It's causing more issues than what it solves, so let's just revert it and wait for #575 (qt6) to do it properly

### CODE REVIEW

**Review by Scrumplex — APPROVED** [review]

**Review by txtsd — APPROVED** [review]
:(

**Comment by txtsd** [comment]
Actually, why not just change the version check to >=Qt6?

**Comment by DioEgizio** [comment]
> Actually, why not just change the version check to >Qt6?

#575 already does that

**Comment by DioEgizio** [comment]
oh no nvm

**Comment by DioEgizio** [comment]
Let's let scrumplex do it in that pr lol

**Review by flowln — APPROVED** [review]

**Pull request merged**
