### PR TITLE
Modernize codebase with clang-tidy

### PR DESCRIPTION
**Pull request by txtsd**
## Checks run so far:

- [x] [cppcoreguidelines-init-variables](https://clang.llvm.org/extra/clang-tidy/checks/cppcoreguidelines-init-variables.html)
- [ ] [cppcoreguidelines-prefer-member-initializer](https://clang.llvm.org/extra/clang-tidy/checks/cppcoreguidelines-prefer-member-initializer.html)
- [ ] [cppcoreguidelines-pro-bounds-constant-array-index](https://clang.llvm.org/extra/clang-tidy/checks/cppcoreguidelines-pro-bounds-constant-array-index.html)
- [x] [cppcoreguidelines-pro-type-cstyle-cast](https://clang.llvm.org/extra/clang-tidy/checks/cppcoreguidelines-pro-type-cstyle-cast.html)
- [x] [cppcoreguidelines-pro-type-member-init](https://clang.llvm.org/extra/clang-tidy/checks/cppcoreguidelines-pro-type-member-init.html)
- [x] [cppcoreguidelines-pro-type-static-cast-downcast](https://clang.llvm.org/extra/clang-tidy/checks/cppcoreguidelines-pro-type-static-cast-downcast.html)
- [ ] [cppcoreguidelines-virtual-class-destructor](https://clang.llvm.org/extra/clang-tidy/checks/cppcoreguidelines-virtual-class-destructor.html)
- [x] [llvm-include-order](https://clang.llvm.org/extra/clang-tidy/checks/llvm-include-order.html)
- [ ] [modernize-avoid-c-arrays](https://clang.llvm.org/extra/clang-tidy/checks/modernize-avoid-c-arrays.html)
- [x] [modernize-concat-nested-namespaces](https://clang.llvm.org/extra/clang-tidy/checks/modernize-concat-nested-namespaces.html)
- [x] [modernize-deprecated-headers](https://clang.llvm.org/extra/clang-tidy/checks/modernize-deprecated-headers.html)
- [x] [modernize-deprecated-ios-base-aliases](https://clang.llvm.org/extra/clang-tidy/checks/modernize-deprecated-ios-base-aliases.html)
- [ ] [modernize-loop-convert](https://clang.llvm.org/extra/clang-tidy/checks/modernize-loop-convert.html)
- [x] [modernize-make-shared](https://clang.llvm.org/extra/clang-tidy/checks/modernize-make-shared.html)
- [x] [modernize-make-unique](https://clang.llvm.org/extra/clang-tidy/checks/modernize-make-unique.html)
- [x] [modernize-pass-by-value](https://clang.llvm.org/extra/clang-tidy/checks/modernize-pass-by-value.html)
- [x] [modernize-raw-string-literal](https://clang.llvm.org/extra/clang-tidy/checks/modernize-raw-string-literal.html)
- [x] [modernize-redundant-void-arg](https://clang.llvm.org/extra/clang-tidy/checks/modernize-redundant-void-arg.html)
- [x] [modernize-replace-auto-ptr](https://clang.llvm.org/extra/clang-tidy/checks/modernize-replace-auto-ptr.html)
- [x] [modernize-replace-disallow-copy-and-assign-macro](https://clang.llvm.org/extra/clang-tidy/checks/modernize-replace-disallow-copy-and-assign-macro.html)
- [x] [modernize-replace-random-shuffle](https://clang.llvm.org/extra/clang-tidy/checks/modernize-replace-random-shuffle.html)
- [ ] [modernize-return-braced-init-list](https://clang.llvm.org/extra/clang-tidy/checks/modernize-return-braced-init-list.html)
- [x] [modernize-shrink-to-fit](https://clang.llvm.org/extra/clang-tidy/checks/modernize-shrink-to-fit.html)
- [x] [modernize-unary-static-assert](https://clang.llvm.org/extra/clang-tidy/checks/modernize-unary-static-assert.html)
- [ ] [modernize-use-auto](https://clang.llvm.org/extra/clang-tidy/checks/modernize-use-auto.html)
- [x] [modernize-use-bool-literals](https://clang.llvm.org/extra/clang-tidy/checks/modernize-use-bool-literals.html)
- [x] [modernize-use-default-member-init](https://clang.llvm.org/extra/clang-tidy/checks/modernize-use-default-member-init.html)
- [x] [modernize-use-emplace](https://clang.llvm.org/extra/clang-tidy/checks/modernize-use-emplace.html)
- [x] [modernize-use-equals-default](https://clang.llvm.org/extra/clang-tidy/checks/modernize-use-equals-default.html)
- [x] [modernize-use-equals-delete](https://clang.llvm.org/extra/clang-tidy/checks/modernize-use-equals-delete.html)
- [x] [modernize-use-nodiscard](https://clang.llvm.org/extra/clang-tidy/checks/modernize-use-nodiscard.html)
- [x] [modernize-use-noexcept](https://clang.llvm.org/extra/clang-tidy/checks/modernize-use-noexcept.html)
- [x] [modernize-use-nullptr](https://clang.llvm.org/extra/clang-tidy/checks/modernize-use-nullptr.html)
- [x] [modernize-use-override](https://clang.llvm.org/extra/clang-tidy/checks/modernize-use-override.html)
- [ ] [modernize-use-trailing-return-type](https://clang.llvm.org/extra/clang-tidy/checks/modernize-use-trailing-return-type.html)
- [x] [modernize-use-transparent-functors](https://clang.llvm.org/extra/clang-tidy/checks/modernize-use-transparent-functors.html)
- [x] [modernize-use-uncaught-exceptions](https://clang.llvm.org/extra/clang-tidy/checks/modernize-use-uncaught-exceptions.html)
- [x] [modernize-use-using](https://clang.llvm.org/extra/clang-tidy/checks/modernize-use-using.html)

### CODE REVIEW

**Comment by Scrumplex** [comment]
Nice. We probably should look into deprecation as well. But maybe after one of #90 and #127 is merged.

**Comment by txtsd** [comment]
Sounds good. I'm only doing non-breaking changes as of now. And I'm leaving some checks out until we can get opinions about them.

**Comment by ghost** [comment]
This will make merging absolute cancer btw

**Comment by ghost** [comment]
small amount of changed files

**Comment by txtsd** [comment]
> small amount of changed files

It's ridiculous that there are so many source files in the first place lol.

**Comment by txtsd** [comment]
Okay this is all I'm going to do for now. It doesn't cover all the default checks by `clang-tidy` but it's good enough for a code modernization attempt.

The unchecked `modernize-*` checks reduce readability (in my opinion) either by converting variables to `auto`, or by omitting classnames. I have chosen to leave them out.

The unchecked `cppcoreguidelines-*` checks have no automatic fixes, so let me know if you'd like them to be implemented.

Many of these commits make changes in the included libraries too. Let me know if that's alright. @Scrumplex hinted at the possibility of moving the libraries out of this repo, so I can drop those changes from here and reapply them in the future library repos.

Also, there were some over-corrections applied by `clang-tidy` which I had to fix manually. Just an fyi.

Finally, since this touches a LOT of files, I'd like for the test builds to be tested thoroughly for logical errors before this can be considered for a merge.

**Comment by Scrumplex** [comment]
Sounds good. I guess we can keep the changes in `libraries/` for now. Ideally we would want to move all of it out of the repo, if feasible. See #135

**Comment by LennyMcLennington** [comment]
> This will make merging absolute cancer btw

^

**Comment by txtsd** [comment]
@LennyMcLennington I know, but would you rather not?

**Comment by Scrumplex** [comment]
Maybe we should split this up into multiple PRs. Some things like reordering includes should be fine.

Potentially we can also just cherry-pick a few of the smaller commits.

**Review by Scrumplex — CHANGES_REQUESTED** [review]
why was this moved from out of private

**Comment by Scrumplex** [comment]
Oh my god, thanks GitHub. I was reviewing a single commit, but it doesn't link there.

**Comment by txtsd** [comment]
It won't even show me what changes you requested. You're right. I'll split this into multiple PRs. Is one per clang-tidy check alright?

**Comment by CoelacanthusHex** [comment]
One idea is that we can configure CI on PRs to automatically check if PRs are clang-tidy compliant (using our config files, of course), which ensures that our subsequent contributions are more modern and style-consistent.

**Comment by Scrumplex** [comment]
We can do this once MMC adopts a CLA

**Review by timoreo22 — APPROVED** [review]
Well, new license change kinda cuts all merging chances so i'm ok for merge
this does need to be updated for latest changes
NOTE : this will probably cause conflicts in every other PR

**Pull request closed without merging**
