### PR TITLE
Draft: Initial M1 Support

### PR DESCRIPTION
**Pull request by d-513**
This adds support for M1 macs. When using an M1 mac, it will use the mmachina meta server from [ManyMC](https://github.com/MinecraftMachina/ManyMC) [meta-multimc-arm64](https://github.com/MinecraftMachina/meta-multimc-arm64)

Checklist:
- [ ] Get permission from ManyMC and possibly host our own M1 meta repo to integrate with the current setup
- [X] Initial test on M1
- [X] Test X86 build on M1
- [ ] ~~Test native M1 build~~ not happening until Qt6 which will fix the various build errors
- [x] Test game launch on M1
- [X] Test for side effects on other platforms
- [x] Test on x86 macs for side effects

### CODE REVIEW

**Comment by d-513** [comment]
Blocker: We are blocked by MultiMC, and the ManyMC meta repo points to MultiMC log4j things, which cant be downloaded
We should update meta-polymc and make an m1 meta repo

**Comment by kloenk** [comment]
Minecraft 1.18.1 launched natively on m1 and world did load. I just changed the PolyMC UA, to get access to the log4j files.

**Comment by ghost** [comment]
@ViRb3

**Comment by d-513** [comment]
Btw, if manymc doesn't want this, I am happy to close this PR.
I believe this PR would be useful because polymc is now getting its own features, like the recently implemented Mod Downloader.

**Comment by DioEgizio** [comment]
Schermata 2022-02-10 alle 18 56 13


works on intel macs

**Comment by d-513** [comment]
Closing as I have no way to work on this, we need bigger metaserver changes and I don't have an m1 for testing.
If someone wants to do this, feel free to use these changes

**Pull request closed without merging**
