### PR TITLE
Add DOOM SNES source code

### PR DESCRIPTION
**Pull request by billyboybob**
Extremely important change. Please. Please god. If nothing else.

### CODE REVIEW

**Review by FlawlessDeveloper — COMMENTED** [review]
SNEEES

**Comment by Packsolite** [comment]
LGTM!

**Review by junekept — APPROVED** [review]
WOOOOO

**Review by TheFruxz — APPROVED** [review]
Works on Windows 12 for ARM

**Review by kura098123 — APPROVED** [review]

**Comment by Sascha-T** [comment]
lgtm

**Review by Sascha-T — COMMENTED** [review]
yes

**Review by Sascha-T — APPROVED** [review]

**Review by oriyadid — APPROVED** [review]
LGTM

**Comment by AshtakaOOf** [comment]
I approve this amazing PR

**Review by crosby-moe — APPROVED** [review]
yees

**Comment by deltanedas** [comment]
marko zajc

**Review by deltanedas — APPROVED** [review]

**Comment by Zetvue** [comment]
i approve of this

**Pull request closed without merging**
