### PR TITLE
Update metainfo URLs

### PR DESCRIPTION
**Pull request by Scrumplex**

### CODE REVIEW

**Comment by DioEgizio** [comment]
it doesn't make more sense to fix this in polymc.org side?

**Comment by Scrumplex** [comment]
This was already backported for Flatpak, which is probably the most important consumer of this metadata. I think there is no other AppStream-aware distribution that packages PolyMC right now, so we should be fine

**Comment by DioEgizio** [comment]
oh then ok

**Comment by d-513** [comment]
> This was already backported for Flatpak, which is probably the most important consumer of this metadata. I think there is no other AppStream-aware distribution that packages PolyMC right now, so we should be fine

Doesn’t matter the distro, software stores with packagekit will use the meta. However it isn’t really needed as most pepole don’t use software centers. So flatpak is the biggest consumer

**Review by d-513 — APPROVED** [review]

**Review by txtsd — APPROVED** [review]

**Review by ZekeZDev — APPROVED** [review]

**Pull request merged**
