### PR TITLE
Revert lenny being a dumbass

### PR DESCRIPTION
**Pull request by Lutitious**
Signed-off-by: Rahul Imran <notlutitious@gmail.com> suck my balls

### CODE REVIEW

**Comment by EsserGaming** [comment]
:trollface:

**Review by autione — APPROVED** [review]

**Comment by quat1024** [comment]
based !

**Review by quat1024 — APPROVED** [review]

**Comment by EsserGaming** [comment]
stinky derg!

**Review by sussycatgirl — APPROVED** [review]
truly

**Review by EsserGaming — APPROVED** [review]
image

**Pull request closed without merging**
