### PR TITLE
Use light background macOS icon

### PR DESCRIPTION
**Pull request by ryanccn**
This looks better on both light mode and dark mode.

### CODE REVIEW

**Review by Scrumplex — APPROVED** [review]

**Review by txtsd — APPROVED** [review]

**Comment by ryanccn** [comment]
Wait. Let me fix the shadows sometime this week

**Comment by ryanccn** [comment]
this is better

**Comment by Un1q32** [comment]
i like the bigger icon better tbh

**Comment by ryanccn** [comment]
Also, I don’t know if this is an optical illusion or not, but icons with dark backgrounds somehow look *smaller* than those with light backgrounds in the Dock.

**Review by timoreo22 — APPROVED** [review]

**Pull request merged**
