### PR TITLE
Fix broken url in readme

### PR DESCRIPTION
**Pull request by jopejoe1**

### CODE REVIEW

**Review by flowln — APPROVED** [review]

**Review by flowln — APPROVED** [review]
thank u!

**Comment by BeansBeefBroccoli** [comment]
This should probably also be un-capitalized and have a period, right?

**Review by Scrumplex — APPROVED** [review]
Thanks!

**Review by txtsd — APPROVED** [review]

**Comment by flowln** [comment]
wait i approved this twice? o.O

**Comment by txtsd** [comment]
> wait i approved this twice? o.O

Happens lol

**Pull request merged**
