### PR TITLE
Clarified the CONTRIBUTING file

### PR DESCRIPTION
**Pull request by NikNikovsky**

### CODE REVIEW

**Comment by LennyMcLennington** [comment]
This just makes unnecessary edits that make it incorrect. I'd be happy accepting a PR that JUST fixes grammatical errors instead of changing the wording.

There's no need to hyphenate 'open source'.

Removing '-off' from 'signed-off' just makes it incorrect, because cryptographically signing your commits is not the same thing as signing-off your commits.

**Review by LennyMcLennington — CHANGES_REQUESTED** [review]
I've mentioned above what needs to be changed.

**Comment by NikNikovsky** [comment]
Ok, i will. Blame it on grammarly

**Comment by LennyMcLennington** [comment]
I'll blame it on the person that spammed a bunch of PRs to a bunch of projects without even bothering to check whether they were grammatically correct.

**Pull request closed without merging**
