### PR TITLE
Microsoft account only

### PR DESCRIPTION
**Pull request by ghost**
Support for mojang api was removed a few months ago iirc.

### CODE REVIEW

**Comment by DioEgizio** [comment]
no it isn't, they just can't play online anymore

**Comment by ghost** [comment]
Okay, maybe there should be a mention about that?

**Comment by TayouVR** [comment]
we can merge this when mojang eventually shuts down the login servers entirely. Currently mojang account users can still login and play offline.

**Comment by TayouVR** [comment]
where should be a mention about that? Its not up to us to decide what mojang / microsoft do. We just kept legacy login around as it still functions.

**Comment by ghost** [comment]
I meant in the message from multimc about you can only use Mojang accounts offline. Or maybe we should expect everyone knows that.

**Comment by Scrumplex** [comment]
This has been attempted by me in #283 and #354, but as there are still people using Mojang accounts, I wouldn't approve of removing this. But yes, there should be some message about Mojang accounts not being able to play online.

**Comment by ghost** [comment]
I have now updated this PR with a suitable text.

**Review by Scrumplex — APPROVED** [review]

**Review by LennyMcLennington — APPROVED** [review]

**Pull request merged**
