### PR TITLE
Capitalization fix in the README

### PR DESCRIPTION
**Pull request by RaptaG**
:)

### CODE REVIEW

**Review by d-513 — APPROVED** [review]
https://user-images.githubusercontent.com/49000790/172022269-e2f38577-afb4-4d9b-96df-c6ff431b6f53.mp4

**Review by Scrumplex — APPROVED** [review]

**Review by flowln — APPROVED** [review]
:O git blame whoever made such a serious mistake!!!! /j

seriously now, thanks for the contribution :D

**Comment by RaptaG** [comment]
> seriously now, thanks for the contribution :D

You're welcome! I love this project and I wanted to contribute even with this small addition, since my programming knowledge is limited :(

**Comment by BeansBeefBroccoli** [comment]
@flowln https://github.com/RaptaG/PolyMC/commit/02b44256b29fd10499177459e7ff515d7e81c10a

**Comment by Un1q32** [comment]
thank god this was merged polymc was unusable before

**Comment by d-513** [comment]
> thank god this was merged polymc was unusable before

literally ban zeke smith for that completely unacceptable, civilization-ending commit

**Pull request merged**
