### PR TITLE
Load instances no matter their instance type

### PR DESCRIPTION
**Pull request by Scrumplex**
This fixes loading of instances. This bug was introduced by... me! Sorry!

### CODE REVIEW

**Review by ZekeZDev — APPROVED** [review]

**Review by timoreo22 — APPROVED** [review]

**Comment by Scrumplex** [comment]
I added the TODO here, but right now this breaks loading of newly created instances. So merge this for now.

**Comment by LennyMcLennington** [comment]
Instead of changing this to load all instances why don't you fix the code for creating new instances

**Review by LennyMcLennington — APPROVED** [review]

**Comment by Scrumplex** [comment]
> Instead of changing this to load all instances why don't you fix the code for creating new instances

When creating a new instance it doesn't save the `InstanceType` as the default is `OneSix` (defaults aren't written to the file apparently). Now if we register the setting while loading the instance and assume the default for unset values is `Legacy`, it will think that it should be a NullInstance

**Comment by Scrumplex** [comment]
Worst case: Someone tries to load a legacy instance and PolyMC crashes.

**Pull request merged**
