### PR TITLE
Fix circular dependency and typos in metainfo.

### PR DESCRIPTION
**Pull request by ZebulanStanphill**
Should fix recursive dependency issue I was running into with https://github.com/flathub/org.polymc.PolyMC/pull/46.

Also includes some capitalization fixes and Oxford commas because why not.

### CODE REVIEW

**Review by slendidev — CHANGES_REQUESTED** [review]
LGTM but I think the provides is ok

**Comment by ZebulanStanphill** [comment]
I've now split the two changes into separate commits (didn't see that you edited your comment, lol).

**Comment by ZebulanStanphill** [comment]
Also, I'm pretty sure the `<provides>` change is indeed necessary, because Prism Launcher removed it about a year and a half ago to fix the same issue.

**Comment by LennyMcLennington** [comment]
@ZebulanStanphill I think this needs to be backported to release branch and tagged before it can be used in the flatpak

**Pull request merged**
