### PR TITLE
Add basic filtering for mod downloading

### LINKED ISSUE #279: mod version matching is too strict
### Operating System

Linux

### Description of bug

mod installer won't show mods that match major version but not minor, some mods are marked as 1.18 but work on 1.18, 1.18.1, 1.18.2 etc

examples
https://modrinth.com/mod/ebe
https://www.curseforge.com/minecraft/mc-mods/carpet

image

### Steps to reproduce

search for mod for minecraft 1.18 in mod installer  in an instance of minecraft 1.18.1 or 1.18.2

### Suspected cause

_No response_

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### PR DESCRIPTION
**Pull request by flowln**
This adds a new dialog in the mod download dialog, showing options for changing filter options. For now there's only some options related to the MC version showing up. My hope is that this provides a good base for adding more filter options later on, as one sees fit :)

Note: There's some comments on the Dialog code related to another way of filtering by MC versions (between versions *X* and *Y*), but I have not implemented it. I was not sure about how to go about it, so I though it would be better to separate it into another PR for another time :^)

Pics:
(outdated ones)
image
image

(new one)
image

Should close #279.

### CODE REVIEW

**Comment by DioEgizio** [comment]
> This adds a new dialog in the mod download dialog, showing options for changing filter options. For now there's only some options related to the MC version showing up. My hope is that this provides a good base for adding more filter options later on, as one sees fit :)
> 
> Note: There's some comments on the Dialog code related to another way of filtering by MC versions (between versions _X_ and _Y_), but I have not implemented it. I was not sure about how to go about it, so I though it would be better to separate it into another PR for another time :^)
> 
> Pics: image image
> 
> Should close #279.

this looks cool but I think the filter page should have a warning like: "Change this only if you know what you're doing. Some mods downloaded changing this could not work."

**Comment by flowln** [comment]
> this looks cool but I think the filter page should have a warning like: "Change this only if you know what you're doing. Some mods downloaded changing this could not work."

I don't think so. The game not working after you selected a non supported version is evidently your problem, since you selected so. 

Consider that, by default, the filtering will be the same as before: strict to the exact game version. If you go out of your way to change it, having this kind of warning is just getting getting in the users way. It is just one more warning for you to ignore.

**Comment by DioEgizio** [comment]
right but i think users should really understand what they're doing, not "clicking this button makes me download the mod but it crashes"

**Comment by Scrumplex** [comment]
I personally would prefer having a dropdown / combobox instead of a dialog. As long as we don't have other filters it should be better to have a single combobox

**Comment by flowln** [comment]
> right but i think users should really understand what they're doing, not "clicking this button makes me download the mod but it crashes"

Yes, but "I selected a mod that was not marked as available for my specific version and it crashed, seems like the version is really not available for this version yet :(". Tbh I don't have that much of a problem putting such a disclaimer, I just think it is unnecessary bubble wrap for users that **probably** already know at least the basic of how mods work, since they're messing with such thing in a custom launcher after all.

 > I personally would prefer having a dropdown / combobox instead of a dialog. As long as we don't have other filters it should be better to have a single combobox
 
 Indeed, if that was the case, I would agree. The problem comes later, when we think "Well, maybe filter option *X* would be nice". That's the case with the "Between versions *x* and *y*" I mencioned: How would be select those versions *x* and *y* with a single combobox? Besides, what if we want to add a categories filter for only showing "Adventure" mods or something, as both CF and Modrinth support it.

The point is, I think the dialog is a better solution for the longer term, since it allows us to more easily add such features in the future, if we so wish to.

**Comment by Scrumplex** [comment]
I feel like the dialog isn't the best choice from a UX perspective. There is nothing that visually connects the changes you make in the dialog with the actual search. Instead of a dialog, I would prefer having it in the same window as the search itself. Maybe we can use some kind of collapsible panel?

**Comment by flowln** [comment]
The problem I see with this is that the mod list already uses a good deal of space (specially vertical space). Even if the panel was collapsible, when it showed up it would take up a lot of space. This is especially true if we later decide to expand the available filter options.

I do not know what's the best way to approach this either. Maybe we could have a tab, like the Modrinth and CurseForge tabs, for the filter options of both. Or maybe the Filter button could create a page that would temporarily replace the mod list view, while you set the options. Or perhaps doing as you said, but showing each subgroup as a tab in a tabbed layout... Other suggestions are welcome!

It doesn't seem super important that we see both the mod list and the filter options at the same time, since the changes are only applied once you finish your selections and apply it (as of now, when accepting the QDialog). Doing otherwise could incur a lot of needless requests to the mod providers while changing options, which would not be cool...

**Review by ZekeZDev — APPROVED** [review]

**Comment by flowln** [comment]
I changed it from a dialog to a tabbed widget on the mod download dialog itself. Looks like this now: 
new filter options

I hope that's better :^)

Also, if you wish to, you can squash this when merging (talking to whoever will merge, i'm looking at you :eye: :) )

**Comment by Scrumplex** [comment]
Looks cool

**Review by Scrumplex — APPROVED** [review]
I like this.

Maybe we can make the window a little larger by default, but apart from that LGTM.
Thanks!

**Comment by flowln** [comment]
Converted to draft because it's going to conflict with #185

**Comment by Scrumplex** [comment]
I am sure we can get this merged for 1.2.0

**Comment by flowln** [comment]
I'll try to do the #405 thing, but this will also conflict with #431 now!

**Comment by flowln** [comment]
@Scrumplex @txtsd see if this size is fine please :-)

**Comment by Scrumplex** [comment]
> @Scrumplex @txtsd see if this size is fine please :-)

yep looks good

**Comment by txtsd** [comment]
> @txtsd see if this size is fine please :-)

Yep!

**Review by ZekeZDev — APPROVED** [review]

**Review by txtsd — APPROVED** [review]

**Comment by ZekeZDev** [comment]
How close to complete is this, Is it close to being ready to merge?

**Comment by flowln** [comment]
It's ready, but will conflict with #431. Either we merge this and resolve conflicts in #431, or the other way around. I don't mind it either way!

**Comment by ZekeZDev** [comment]
I think it would make sense to merge this first.

**Comment by ZekeZDev** [comment]
@Scrumplex is this ok with you?

**Comment by Un1q32** [comment]
When #431 is merged it might make sense to add an option to enable or disable listing fabric mods on quilt to the widget.

**Comment by Scrumplex** [comment]
> @Scrumplex is this ok with you?

Yeah sure. Don't mind if we merge this one first

**Comment by flowln** [comment]
> Yeah sure. Don't mind if we merge this one first

okay!

> When https://github.com/PolyMC/PolyMC/pull/431 is merged it might make sense to add an option to enable or disable listing fabric mods on quilt to the widget.

For now there's no point in doing so, since they'll be mostly compatible afaik. Later on, when mod providers start supporting Quilt for real, or Fabric compatibility starts to decrease, we can add this!

**Comment by DioEgizio** [comment]
> > Yeah sure. Don't mind if we merge this one first
> 
> okay!
> 
> > When #431 is merged it might make sense to add an option to enable or disable listing fabric mods on quilt to the widget.
> 
> For now there's no point in doing so, since they'll be mostly compatible afaik. Later on, when mod providers start supporting Quilt for real, or Fabric compatibility starts to decrease, we can add this!

Modrinth will support it really soon

**Comment by DioEgizio** [comment]
https://mobile.twitter.com/modrinth/status/1502436206616842243

**Comment by flowln** [comment]
But will there be any mods that work on Fabric that will not work on Quilt, or vice-versa, for the time being? I would guess it will take a while for Fabric mods to start becoming incompatible with Quilt. Besides, the aim of this PR is mostly to lay the foundation for adding filters to the mod search. I think adding this other filter should go into a separate PR.

**Comment by DioEgizio** [comment]
> But will there be any mods that work on Fabric that will not work on Quilt, or vice-versa, for the time being? I would guess it will take a while for Fabric mods to start becoming incompatible with Quilt. Besides, the aim of this PR is mostly to lay the foundation for adding filters to the mod search. I think adding this other filter should go into a separate PR.

Yeah that's true.

**Pull request merged**
