### PR TITLE
fix nix build

### PR DESCRIPTION
**Pull request by LordMZTE**
The nix flake builds & runs on NixOS now.

### CODE REVIEW

**Comment by ghost** [comment]
What does this change? Did it not build before?

**Comment by LordMZTE** [comment]
> What does this change? Did it not build before?

Yes, it wasn't building previously due to changes in Nix's Qt wrapper.

This also adds another set of unwrapped packages that include the original binaries where the previously only wrapped packages were exported (Nix wraps Qt apps in order to set some environment variables by default).

**Comment by LordMZTE** [comment]
> What does this change? Did it not build before?

Yes, it wasn't building previously due to changes in Nix's Qt wrapper.

This also adds another set of unwrapped packages that include the original binaries where the previously only wrapped packages were exported (Nix wraps Qt apps in order to set some environment variables by default).

**Comment by LordMZTE** [comment]
> What does this change? Did it not build before?

Yes, it wasn't building previously due to changes in Nix's Qt wrapper.

This also adds another set of unwrapped packages that include the original binaries where the previously only wrapped packages were exported (Nix wraps Qt apps in order to set some environment variables by default).

**Comment by ghost** [comment]
Okay, we can only merge this if it for sure doesn't break any supported Nix versions.

**Comment by LordMZTE** [comment]
> Okay, we can only merge this if it for sure doesn't break any supported Nix versions.

What do you mean? All relevant APIs are coming from nixpkgs, the version of which is governed by the flake lock file included in this repository. There are no external dependencies, as per Nix's design. I do not understand why the previous version would ever have worked for this reason, I think it was simply just broken on our side.

**Comment by ghost** [comment]
Ok. Not familiar with Nix at all so idk

**Review by ghost — APPROVED** [review]

**Comment by ghost** [comment]
Can you fix the DCO?

**Review by Kaydax — APPROVED** [review]

**Pull request merged**
