### PR TITLE
Correctly handle disabled mods with metadata

### PR DESCRIPTION
**Pull request by flowln**
Again fixing issues i made because im dumb, hooray!

Avoids mod duping when disabling mods:
lots of LazyDFU

### CODE REVIEW

**Review by timoreo22 — APPROVED** [review]

**Comment by DioEgizio** [comment]
I didn't know you liked lazydfu that much :ioa:

**Review by d-513 — APPROVED** [review]

**Review by txtsd — APPROVED** [review]

**Comment by BeansBeefBroccoli** [comment]
LazyDFU is a good mod

**Comment by DioEgizio** [comment]
works so great that clicking the mods tab makes polymc segfault D:

**Comment by DioEgizio** [comment]
oh lmao it explodes when there's the same mod but 2, one disabled and one enabled

**Comment by flowln** [comment]
rebased and fixed the segfault :)

**Pull request merged**
