### PR TITLE
Add a .clang-format

### PR DESCRIPTION
**Pull request by ryanccn**
This is the one @flowln sent in Discord

### CODE REVIEW

**Comment by flowln** [comment]
For clarification, the ones with `# changed` are the ones that differ from the Chromium base I started with.
Also, we need to properly organize a voting to gather peoples opinions on those changes :)

**Comment by Scrumplex** [comment]
Wouldn't it be possible to use `BasedOnStyle:  Chromium` and then only change the stuff we want? That way the file would be more compact.

**Comment by ryanccn** [comment]
> Wouldn't it be possible to use `BasedOnStyle: Chromium` and then only change the stuff we want? That way the file would be more compact.

I don't know. When `clang-format` generates the file "based on another style" it recreates everything

**Comment by ryanccn** [comment]
just 221 lines :pofat:

**Comment by Scrumplex** [comment]
> just 221 lines :pofat:

It's more about maintaining that file, than the size. It's easier to tell if it just says
```
BasedOnStyle: Chromium
opt1: 420
opt2: 69
opt3: 1337
opt4: 42069
```
instead of going through the whole file

**Comment by ryanccn** [comment]
Hmm.

**Comment by ryanccn** [comment]
OK cleaned up `.clang-format` to just contain the changed ones

**Review by Scrumplex — APPROVED** [review]
Cool

**Review by txtsd — APPROVED** [review]

**Review by timoreo22 — APPROVED** [review]

**Pull request merged**
