### PR TITLE
move fabric up the modloader list

### PR DESCRIPTION
**Pull request by d-513**
Fabric is a more user-respecting mod loader, as a FOSS launcher I think we should put it above forge

### CODE REVIEW

**Comment by DioEgizio** [comment]
When #185 gets merged you should move up quilt tho

**Review by ZekeZDev — APPROVED** [review]

**Comment by Newbytee** [comment]
> Fabric is a more user-respecting mod loader

Could you elaborate on how it is more user-respecting?

**Comment by glowiak** [comment]
What's wrong with Forge? All major mods are on Forge. It's open source too --> http://github.com/minecraftforge

**Comment by d-513** [comment]
image

found in forge jar meta files.
Plus, lots of other controversies out of the scope of this PR. 
As for "major mods" - this is not removing forge support.

**Comment by d-513** [comment]
anyways I feel like this is unexpected from a UI perspective so might aswell close this PR.

**Pull request closed without merging**
