### PR TITLE
Code of Conduct simplified

### PR DESCRIPTION
**Pull request by gabrielvicenteYT**
Now there's surely no political reasons or anything.

### CODE REVIEW

**Comment by jdpatdiscord** [comment]
What is the reason for opening something like this at all?

**Comment by gabrielvicenteYT** [comment]
> What is the reason for opening something like this at all?

To prove (or disprove?) that Lenny is NOT a radical, and just wants to do good...

**Comment by jdpatdiscord** [comment]
There's nothing to prove. People have already chosen to draw themselves along ideological lines and then the rest of the news media apparatus dragged along most of the users. But, if you're curious about Lenny, ask him questions in the Discord. Joke CoC PRs have already been rejected in the past, as it's his decision to have none at all.

**Comment by LennyMcLennington** [comment]
@jdpatdiscord All CoCs are jokes, so specifying *joke* CoCs is redundant 😄

But on a serious note, @gabrielvicenteYT while this CoC is probably the most reasonable one I've seen, it still just restates what should be obvious and I don't think it really helps so I won't merge it but thank you for the well meaning sentiment.

**Comment by Kaydax** [comment]
LGTM

**Comment by gabrielvicenteYT** [comment]
> @jdpatdiscord All CoCs are jokes, so specifying _joke_ CoCs is redundant 😄
> 
> But on a serious note, @gabrielvicenteYT while this CoC is probably the most reasonable one I've seen, it still just restates what should be obvious and I don't think it really helps so I won't merge it but thank you for the well meaning sentiment.

Thanks! By the way, I'm quite neutral about the Prism Launcher / PolyMC scandal, I kind of just let myself go, and respect both sides. Either way, I'm here to respect both 'lefties', and 'righties'; therefore, I rest my case.

**Pull request closed without merging**
