### PR TITLE
change 'Install Mods' -> 'Download Mods' and change position

### LINKED ISSUE #218: Move Install Mods above Remove, Enable, Disable
### Role

I download mods

### Suggestion

Move Install Mods above Remove, Enable, Disable divider

### Benefit

Currently both the version folder and the mods folder have an install mods button one moves you to mods and the other acutally opens the mod installer.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Screenshot_20220303_113944
Screenshot_20220303_113815
Moving the Install mods button underneath Add in the mod loader page would make more sense and possibly renaming it to something like Download Mods or Mod Installer would reduce confusion.

### PR DESCRIPTION
**Pull request by flowln**
Fixes #218.

Also, this part of the code-base really needs some love it seems :/

### CODE REVIEW

**Review by timoreo22 — CHANGES_REQUESTED** [review]
This reintroduces a bug where the Downloads Mods is present in the shader & resource pack tab

You see, even tho this class is called ModFolderPage, it's actually the parent class for theses two too, the only solution i found at the time was to create the button inside of the class, because only there i can check the id making sure it's not from another page

To make this code cleaner we could separate ModFolderPage into two classes, one with virtual members, where the other classes would inherit, and one dedicated only for the mod folder, but that's maybe for another PR.

**Comment by flowln** [comment]
> You see, even tho this class is called ModFolderPage, it's actually the parent class for theses two too, the only solution i found at the time was to create the button inside of the class, because only there i can check the id making sure it's not from another page

Well, that's... an interesting design decision for sure... I'll make a hack for now, and maybe do some cleaning up in another PR, if that's ok by you people, because I could not find a way to insert the button at the desired position, since inserting it before the 'Add' button puts the 'Download' one above it, and before the 'Remove' one puts it after the separator, which doesn't look very nice...

**Comment by LennyMcLennington** [comment]
Do you really need to do anything other than `setVisible(false);`?

**Comment by timoreo22** [comment]
This still creates a wierd gap on the other ones, as far as i know there is no way to fix that gap once the ui is built
image

**Comment by ZekeZDev** [comment]
Since this seems like an annoying part of code cleanup I think it might be better to just rename the install mods to download mods and leave it in current position and focus on ui cleanup for some of the bug fix updates. I am still not sure which context sounds better "Mod installer" or "Download Mods" or maybe just "search" I think search would make more sense if we can have it above or below the Add button.

**Comment by flowln** [comment]
> Do you really need to do anything other than `setVisible(false);`?

Yeah, doing this just grays out the text, but the button stays there...

> This still creates a wierd gap on the other ones, as far as i know there is no way to fix that gap once the ui is built

Oh, on my end the separator is invisible, so I thought it was ok, but it seems like that's not the case ;--;

> or maybe just "search"

Won't this create confusion on whether you're searching for a mod to download or searching for a mod in your installed mods?

Ok, I think I can do the name change @LennyMcLennington suggested on Discord, and put the download button at the top, it is still better than letting it at the same place as it is now imo.

**Comment by DioEgizio** [comment]
> Since this seems like an annoying part of code cleanup I think it might be better to just rename the install mods to download mods and leave it in current position and focus on ui cleanup for some of the bug fix updates. I am still not sure which context sounds better "Mod installer" or "Download Mods" or maybe just "search" I think search would make more sense if we can have it above or below the Add button.

I think the best would be merging add and install mod as just one button but naming it just "Install Mods", but that should be another pr

**Comment by DioEgizio** [comment]
Ok latest commit of this works fine

**Review by timoreo22 — APPROVED** [review]
All good now !

**Review by ZekeZDev — APPROVED** [review]

**Review by Scrumplex — APPROVED** [review]

**Pull request merged**
