### PR TITLE
Fix translatable strings

### LINKED ISSUE #281: Remove words like CurseForge, Discord, Minecraft from translations; Minor spelling issues.
### Role

I translate on weblate

### Suggestion

No brand names in translations

### Benefit

Correct translation progress

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

They are untranslatable and unless a translator manually dismisses all the checks they are the reason translations progress is lower than it should be e.g. 99% instead 100%.

Also, sometimes Java, Minecraft, or Forge (sometimes written as Minecraft Forge) is not capitalized, I think this is an error.
https://github.com/PolyMC/Translations/blob/8f65ab199ae9be92fa3ab8ec0b2a45625c297fee/template.pot#L631
https://github.com/PolyMC/Translations/blob/8f65ab199ae9be92fa3ab8ec0b2a45625c297fee/template.pot#L648
https://github.com/PolyMC/Translations/blob/8f65ab199ae9be92fa3ab8ec0b2a45625c297fee/template.pot#L938
https://github.com/PolyMC/Translations/blob/8f65ab199ae9be92fa3ab8ec0b2a45625c297fee/template.pot#L1187
https://github.com/PolyMC/Translations/blob/8f65ab199ae9be92fa3ab8ec0b2a45625c297fee/template.pot#L1552
https://github.com/PolyMC/Translations/blob/8f65ab199ae9be92fa3ab8ec0b2a45625c297fee/template.pot#L1939
https://github.com/PolyMC/Translations/blob/8f65ab199ae9be92fa3ab8ec0b2a45625c297fee/template.pot#L2003
https://github.com/PolyMC/Translations/blob/8f65ab199ae9be92fa3ab8ec0b2a45625c297fee/template.pot#L2434
https://github.com/PolyMC/Translations/blob/8f65ab199ae9be92fa3ab8ec0b2a45625c297fee/template.pot#L3598
https://github.com/PolyMC/Translations/blob/8f65ab199ae9be92fa3ab8ec0b2a45625c297fee/template.pot#L3602
https://github.com/PolyMC/Translations/blob/8f65ab199ae9be92fa3ab8ec0b2a45625c297fee/template.pot#L3722
https://github.com/PolyMC/Translations/blob/8f65ab199ae9be92fa3ab8ec0b2a45625c297fee/template.pot#L3727
https://github.com/PolyMC/Translations/blob/8f65ab199ae9be92fa3ab8ec0b2a45625c297fee/template.pot#L3728
https://github.com/PolyMC/Translations/blob/8f65ab199ae9be92fa3ab8ec0b2a45625c297fee/template.pot#L4075

### PR DESCRIPTION
**Pull request by Scrumplex**
General cleanup of translatable strings.

Closes #281

### CODE REVIEW

**Comment by Scrumplex** [comment]
@RDKRACZ Feel free to collect more typos here

**Comment by flowln** [comment]
@Scrumplex this will conflict with removing paste.polymc.org from the paste services. Do you want to handle the merge in here or do you want me to in that other PR?

**Comment by Scrumplex** [comment]
@flowln let's do it in your PR. Makes it easier to track later on, if someone wants to find out why it was removed.

**Comment by K0-RR** [comment]
Missing `?` [here](https://hosted.weblate.org/translate/polymc/polymc/pl/?checksum=a5e14d09b3d09397).
What about https://github.com/PolyMC/Translations/issues/8#issuecomment-1066816416?
A space before a dot [there](https://github.com/PolyMC/Translations/blob/3cfd21e16ea6374a27dc07b12d9e62b03540955d/.template.ts#L632) and 5 other times in different lines with the same text.
Double space after `-XX:InitialHeapSize` [here](https://github.com/PolyMC/Translations/blob/master/.template.ts#L4642).
A bunch of stuff is also reported there #281.

Off topic: May I ask what is [Flame](https://github.com/PolyMC/PolyMC/tree/develop/launcher/ui/pages/modplatform/flame)? I can't find anything on the web.

**Comment by DioEgizio** [comment]
> Missing `?` [here](https://hosted.weblate.org/translate/polymc/polymc/pl/?checksum=a5e14d09b3d09397). What about [PolyMC/Translations#8 (comment)](https://github.com/PolyMC/Translations/issues/8#issuecomment-1066816416)? A space before a dot [there](https://github.com/PolyMC/Translations/blob/3cfd21e16ea6374a27dc07b12d9e62b03540955d/.template.ts#L632) and 5 other times in different lines with the same text. Double space after `-XX:InitialHeapSize` [here](https://github.com/PolyMC/Translations/blob/master/.template.ts#L4642). A bunch of stuff is also reported there #281.
> 
> Off topic: May I ask what is [Flame](https://github.com/PolyMC/PolyMC/tree/develop/launcher/ui/pages/modplatform/flame)? I can't find anything on the web.

Flame is the codename of CurseForge in the codebase

**Comment by K0-RR** [comment]
I think the words MCEdit and a standalone Minecraft can also be removed from translations.

**Comment by Scrumplex** [comment]
> I think the words MCEdit and a standalone Minecraft can also be removed from translations.

I think Minecraft is translated in Chinese for example

**Review by ZekeZDev — APPROVED** [review]

**Review by txtsd — APPROVED** [review]

**Review by cozyGalvinism — APPROVED** [review]

**Review by d-513 — APPROVED** [review]

**Review by timoreo22 — APPROVED** [review]

**Pull request merged**
