### PR TITLE
Add additional architecture + OS checks

### PR DESCRIPTION
**Pull request by rrrogalski**
It is now basically on my bukkit list to get MC running on every target listed here (already done ppc and sparc, kinda). Also, note the lack of loongarch- F that japcrap.

### CODE REVIEW

**Comment by rrrogalski** [comment]
ack wait pushed in a broken state i think

**Comment by rrrogalski** [comment]
fixed now

**Comment by glowiak** [comment]
@Richard-Rogalski Just a sidenote, that PolyMC cannot be compiled on NetBSD due to missing libraries

**Comment by slendidev** [comment]
"android"?????

**Comment by rrrogalski** [comment]
You can run java minecraft on android, tho you will need something like VNC to play it. 

I did not know that about netbsd, hopefully they catch up soon :)

**Comment by glowiak** [comment]
@Richard-Rogalski 

> You can run java minecraft on android, tho you will need something like VNC to play it.
> 
> I did not know that about netbsd, hopefully they catch up soon :)

While Minecraft itself can be run on NetBSD (I am the first one who managed to compile LWJGL for this platform btw), there are some missing Qt libraries and unusual locations for known files NetBSD uses.

Once I have managed to compile PolyMC on NetBSD, but it was very broken (for example, no icons were visible), and could not launch the game. Additionally, it required to modify the system itself to get it compiled and running.

**Comment by glowiak** [comment]
And required manually building some missing libraries.

After all, NetBSD is one of the least used BSD platforms overall (at least on desktop), and number of users playing Minecraft there is probably 0, or too low to care about it.

**Comment by rrrogalski** [comment]
So what was holding this back?

**Comment by slendidev** [comment]
PolyMC uses multiple windows. I do not see how this could possibly work on Android. I don't think support should be added just because it builds, because it can be broken in other ways at runtime.

**Pull request merged**
