### PR TITLE
Revert OpenBSD support

### PR DESCRIPTION
**Pull request by glowiak**

### CODE REVIEW

**Comment by DioEgizio** [comment]
?

**Comment by glowiak** [comment]
I am reverting all my commits to pmc, because this launcher becomes politic. Already removed my ports from the website.

**Comment by DioEgizio** [comment]
?

**Comment by glowiak** [comment]
https://github.com/PolyMC/polymc.github.io/pull/154

**Comment by glowiak** [comment]
Is it so hard to just remove three lines of code?

**Comment by ZekeZDev** [comment]
Sure

**Review by ZekeZDev — APPROVED** [review]

**Review by Scrumplex — APPROVED** [review]

**Review by flowln — APPROVED** [review]

**Review by d-513 — APPROVED** [review]

**Comment by Titaniumtown** [comment]
good riddance

**Pull request merged**
