### PR TITLE
Make develop and stable branches compatible

### PR DESCRIPTION
**Pull request by Scrumplex**
This PR effectively doesn't change anything. Just making it, so we can merge develop into stable in the future. We need to work on our Git workflow

### CODE REVIEW

**Review by txtsd — APPROVED** [review]

**Comment by txtsd** [comment]
We should only merge PRs with the correct milestone, I suppose. Did you have something else in mind?

**Comment by d-513** [comment]
I don't like this. Makes git history dirty

**Comment by Scrumplex** [comment]
we are kinda forced, otherwise we can't merge develop into master. See https://github.com/PolyMC/PolyMC/compare/stable...develop

**Review by ZekeZDev — APPROVED** [review]

**Review by d-513 — APPROVED** [review]
but we should find a better way for next versions

**Comment by Scrumplex** [comment]
Yes

**Pull request merged**
