### PR TITLE
Customizability of the toolbar

### PR DESCRIPTION
**Pull request by ryanccn**
Sometimes it could be a bit distracting and also may look ugly to some people.

_please don't attack me for criticizing polycat_

### CODE REVIEW

**Comment by ZekeZDev** [comment]
😠

**Comment by LennyMcLennington** [comment]
There's already an option to hide it at the top of the main window. It's even hidden by default.

**Comment by DioEgizio** [comment]
No u

**Comment by timoreo22** [comment]
Should probably be replaced by a configuration option to customize the cat, maybe replacing current button, allowing for different cats

**Comment by LennyMcLennington** [comment]
Also there isn't a "PolyCat" in the launcher, it's still just background cat.

**Comment by ryanccn** [comment]
@LennyMcLennington is there?

is it because I'm on macOS

**Comment by LennyMcLennington** [comment]
> @LennyMcLennington is there?

Yes, the button with the cat icon will show or hide the background cat.

**Comment by ryanccn** [comment]
> Should probably be replaced by a configuration option to customize the cat, maybe replacing current button, allowing for different cats

@timoreo22 I think that's another feature (#504)

It's not really related, could have in the future more options in the new PolyCat group

**Comment by LennyMcLennington** [comment]
> oh. I mean hide the button

Instead of that why not have toolbar configuration like this instead

https://docs.kde.org/stable5/en/khelpcenter/fundamentals/config.html#toolbars

**Comment by ryanccn** [comment]
Ah. Very complicated

**Comment by DioEgizio** [comment]
No this pr makes me sad :sad_tater:

**Comment by kthchew** [comment]
I don't really see a reason to add an option to hide this specific button.

It's seems really specific and probably isn't worth the added code and setting to do this for a single button. I feel like most people probably wouldn't even really feel the need (or want) to do this. Something generic (like @LennyMcLennington mentioned) would be better, if it's necessary at all (I feel like it would just add additional complexity for little gain, since the tool bar doesn't really have a lot of options anyway).

**Comment by ryanccn** [comment]
Screen Shot 2022-05-25 at 09 37 31

something like this?

**Comment by ryanccn** [comment]
let me close this

**Pull request closed without merging**
