### PR TITLE
Use single-space unicode character for checkmark in mod list

### LINKED ISSUE #942: mods list on launch is broken on macos in develop
### Operating System

macOS

### Version of PolyMC

PolyMC 1.4.0 (develop)

### Description of bug

image

### Steps to reproduce

- open an instance
- see the mods list

### Suspected cause

maybe qt 6?

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### PR DESCRIPTION
**Pull request by flowln**
Fixes #942

This also caused some issues with nvim previously :sweat_smile:

### CODE REVIEW

**Comment by Scrumplex** [comment]
I think this now needs to have a space after the `]`

**Comment by flowln** [comment]
> I think this now needs to have a space after the `]`

image
~doesn't look like so, when i said 'single-spaced' i meant that, for some unicode-weirdness thingy, it used two characters in the code, but it has always appeared as a single one iirc~ ignore what i said. im very dum dum. yes you're correct

**Review by Scrumplex — APPROVED** [review]

**Review by kthchew — COMMENTED** [review]
Spacing is kind of odd compared to folders/disabled mods on macOS, but it works 👍🏼 

Screen Shot 2022-07-22 at 3 13 28 PM

**Comment by Scrumplex** [comment]
Maybe replace the other characters as well?

Maybe `×` for disabled and `◯` for directories?

Edit: or maybe `✖` and `~`

**Comment by flowln** [comment]
image
looks like this for me now

**Review by txtsd — APPROVED** [review]

**Comment by txtsd** [comment]
Will this go in 1.4.0?

**Comment by Scrumplex** [comment]
Let's just move it to 1.4.1

**Comment by DioEgizio** [comment]
i mean it's a very simple change, maybe we could get it in 1.4.0

**Review by timoreo22 — APPROVED** [review]

**Pull request merged**
