### PR TITLE
Upstream update

### PR DESCRIPTION
**Pull request by d-513**
updated to upstream multimc commits, some bugfixes and BSD Support (Still with peterix shitty installer, so we may have to do proper bsd packaging)

This was barely tested, im still testing it so this is kind of a "draft", but if others test and its stable its good to go

### CODE REVIEW

**Comment by ghost** [comment]
Could you rebase commit 01e4e62 ("clearer difference with binaries"), and its merge, out of existence, because it doesn't apply to PolyMC? Thanks!

**Comment by d-513** [comment]
> Could you rebase commit [01e4e62](https://github.com/PolyMC/PolyMC/commit/01e4e62de354db05b9536a51e863b3b21a446eb4) ("clearer difference with binaries"), and its merge, out of existence, because it doesn't apply to PolyMC? Thanks!

Hey, idk if I messed up something in git, but when resolving conflicts I did not accept the incoming change, so that doesnt apply in the BUILD.md file

**Comment by ghost** [comment]
ok cool

**Comment by d-513** [comment]
> ok cool

also please make a new tag with the changes or force push so that I can get working on flathub flatpak

**Comment by ghost** [comment]
I'll add the temporary logo, or i could add the vectorized Ouroboros that lovetocode999 also made. Will do that in a bit because I have to watch my dogs right now

**Comment by d-513** [comment]
> I'll add the temporary logo, or i could add the vectorized Ouroboros that lovetocode999 also made. Will do that in a bit because I have to watch my dogs right now

Ok, thanks. Keep in mind the vectorized Ouroboros is just the PNG embedded as base64 in svg, its no different than png format

**Comment by ghost** [comment]
Lenny actually made a cool version that's actually raster and not just a PNG so im going to use that

**Pull request merged**
