### PR TITLE
Fix release workflow

### PR DESCRIPTION
**Pull request by Scrumplex**
oopsie

### CODE REVIEW

**Review by flowln — APPROVED** [review]
dco: the greatest enemy of Scrumplex

**Comment by DioEgizio** [comment]
> dco: the greatest enemy of Scrumplex

get DCOd

**Comment by Scrumplex** [comment]
Running this release workflow at: https://github.com/Scrumplex/PolyMC/actions/runs/2666202144

**Review by timoreo22 — APPROVED** [review]

**Review by txtsd — APPROVED** [review]

**Comment by DioEgizio** [comment]
3 approvals 👀

**Pull request merged**
