### PR TITLE
Fix regex for WinGet Releaser

### PR DESCRIPTION
**Pull request by russellbanks**
I'm uncertain so tagging @vedantmgoyal2009 and putting as draft.

Closes https://github.com/PolyMC/PolyMC/pull/1120

### CODE REVIEW

**Review by vedantmgoyal9 — APPROVED** [review]

**Comment by Scrumplex** [comment]
Not sure if this fixes anything. I would assume that the regex is matched against each binary separately. The reason why `$` fixes it in your regex tool up there, is because it probably operates in multi-line mode.

I think the regex just needs to be even stricter like `PolyMC-Windows-Setup-[0-9.]+\.exe`

**Comment by russellbanks** [comment]
> I think the regex just needs to be even stricter like `PolyMC-Windows-Setup-[0-9.]+\.exe`

As it seems now though (the way it is currently), the regex seems to correctly identify the newer exe as the right installer and to not include the legacy. We could try making it stricter like this, but I'll see if @vedantmgoyal2009 has any ideas, as it should work.

**Comment by vedantmgoyal9** [comment]
* https://github.com/PolyMC/PolyMC/pull/994 was made on July 29 after the [1.4.1](https://github.com/PolyMC/PolyMC/releases/tag/1.4.1) release on July 28 was not published to WinGet. The PR actually fixes the issue but it seems like the commit 22f5011451088857d470733aed4b47952eb2887a didn't get included in [1.4.2](https://github.com/PolyMC/PolyMC/tree/1.4.2) release tag.

GitHub Action runs the workflow from the [`winget.yml` file present in 1.4.2 tag](https://github.com/PolyMC/PolyMC/blob/1.4.2/.github/workflows/winget.yml) (and not from the default branch `develop`), where Installers Regex is still set to `\.exe$` and is why the workflow still fails. This can be verified when you select `View workflow file` option which can be found as shown in the screenshot.

image

---

image

Also, re-running the workflow won't help either unless the commit 22f5011451088857d470733aed4b47952eb2887a  is cherry-picked onto the 1.4.2 release tag.

**Comment by vedantmgoyal9** [comment]
* Thus, there isn't any need to merge any PR since the issue has been fixed by @Scrumplex. After cherry-picking the commit, the re-running the workflow would work, but since https://github.com/PolyMC/PolyMC/pull/1120 tells that it has already been added in https://github.com/microsoft/winget-pkgs/pull/79165, there's no need to do that.

**Comment by russellbanks** [comment]
Perfect, thank you for finding this out.

**Pull request closed without merging**
