### PR TITLE
Add CMake option to enable stricter DRM

### PR DESCRIPTION
**Pull request by LennyMcLennington**

### CODE REVIEW

**Review by Sightem — APPROVED** [review]

**Review by slendidev — APPROVED** [review]
Fix DCO, otherwise LGTM

**Review by Kaydax — APPROVED** [review]

**Comment by ghost** [comment]
"Noo how dare you disable DRM that only harms users and does nothing to stop piracy"

**Comment by LennyMcLennington** [comment]
That issue https://github.com/QuiltMC/cozy-discord/issues/79 is actually hilarious. What's the warning gonna say? WARNING: THIS LAUNCHER HAS LESS RESTRICTIONS ON HOW YOU CAN USE IT, PLEASE USE \<ALTERNATIVE LAUNCHER\> INSTEAD, SO YOU CAN BE MORE RESTRICTED!!!

LMFAO.

**Comment by ghost** [comment]
Average Discord user:

**Comment by LennyMcLennington** [comment]
I recommend anyone viewing this PR from a link where someone is crying about "piracy" to take a minute to really think critically about why they support Digital Restrictions Management and why they think a lack of such restrictions management automatically means the purpose is piracy. Lack of Digital Restrictions Management is not the same as piracy. I would invite people to read this rationale instead of blindly shouting "PIRACY!!!" and advocating for more restrictive software. At the end of the day, Digital Restrictions Management hurts honest, legitimate users more than anyone else.

DRM as a way to supposedly prevent "piracy" is implemented at the expense of legitimate paying users of the software. It is a form of collective punishment against these users because a company feels that the users are not to be trusted with a piece of software that they paid to use.

Minecraft (Java Edition) so far has no such Digital Restrictions Management in the game client itself. It makes no sense to force such Digital Restrictions Management onto users in a libre launcher for the game, unless Minecraft itself made it a requirement. This launcher is intended to be used by people who own the game legitimately, and the launcher is made explicitly for that purpose. The fight against a few pirates is a waste of time for both developers and legitimate users. The main concern for a libre launcher should be what is best for the legitimate users. The side effect may be that pirates take advantage of that, but that is not my main concern. The main concern for me is to have a better experience for legitimate users. The software should *not* be defective by design because you have pirates in mind, it should be designed with the legitimate users in mind.

Here are some links that may be of use to people:

- Richard Stallman's thoughts on so-called "piracy" and DRM https://stallman.org/articles/end-war-on-sharing.html
- The Free Sofrware Foundation's "defective by design" campaign: https://www.defectivebydesign.org/what_is_drm

**Pull request merged**
