### PR TITLE
Customizability of the toolbar

### PR DESCRIPTION
**Pull request by ryanccn**
Supersedes #636

Mockup:

image

### CODE REVIEW

**Comment by anoraktrend** [comment]
Neat, seems like a good idea

**Comment by BeansBeefBroccoli** [comment]
@anoraktrend Neat is a mod by Vazkii.

**Comment by ryanccn** [comment]
I'm going to work on this PR in the summer, after exams are done.

*please don't take this away from me*

**Comment by flowln** [comment]
any progress on this?

**Comment by ryanccn** [comment]
I am rather busy

**Comment by ryanccn** [comment]
? what

**Pull request closed without merging**
