### PR TITLE
fix: work around ubuntu 22.04 openssl appimage issues by copying openssl libs

### PR DESCRIPTION
**Pull request by DioEgizio**
terrible hack but it works™️

### CODE REVIEW

**Comment by txtsd** [comment]
Link to issues pls

**Comment by DioEgizio** [comment]
literally run the current appimage on Ubuntu 22.04, try to open anything that uses networking and see

**Review by flowln — APPROVED** [review]
bubuntu moment

**Review by txtsd — APPROVED** [review]

**Review by timoreo22 — APPROVED** [review]
When you update to versions even rolling release distros didn't update to

**Comment by DioEgizio** [comment]
but pipewire is too early to add, right canonical?😞

**Review by Scrumplex — COMMENTED** [review]
Post merge review

**Pull request merged**
