### PR TITLE
Merge stable into develop

### PR DESCRIPTION
**Pull request by Scrumplex**
Develop is two commits behind stable. 

- Merge stable into develop
- When there is a conflict, accept our changes
- Effectively nothing changed

Now we can merge into stable once we release a new version.

### CODE REVIEW

**Review by timoreo22 — APPROVED** [review]
alright

**Comment by Scrumplex** [comment]
> alright

hey you forgot to review lines 69 through 420

**Comment by DioEgizio** [comment]
Meta is on develop too tho. Also version was backported by dada

**Comment by timoreo22** [comment]
this pr effectively does no files change, it just makes it able to merge develop into stable later

**Comment by DioEgizio** [comment]
oh

**Review by txtsd — APPROVED** [review]

**Review by d-513 — APPROVED** [review]

**Pull request merged**
