### PR TITLE
UI/UX tweaks and quality of life

### PR DESCRIPTION
**Pull request by ZekeZDev**
This has turned into quite a large amount of tweaks I have removed and added some new functionality and tweaked some existing functionality. The major noticeable changes are:

- Redundant titles removed
Before:
image
After:
image
This affects all pages including, settings, instance settings, instance creation, mod downloader.

- Also pictured above are search filters to be consistent now have placeholder text instead of filter: [search] it is now [Search and filter...]

- Rolypoly icon addded to icon selection
image

- Default instance icon is now the launcher logo
- Vanilla renamed to Custom, icon changed to launcher logo and tab background removed
- "Import from zip" renamed to "Import file"
- Profiles renamed to Accounts to keep consistency with other references
- install mods in version page removed

### CODE REVIEW

**Comment by DioEgizio** [comment]
image

image

there should be some spacing there imo

**Comment by DioEgizio** [comment]
not correctly alligned


not correctly alligned

also it's not correctly alligned which is triggering me

**Comment by ZekeSmith** [comment]
Which part?

**Comment by TayouVR** [comment]
tested it out too and I do agree, there needs to be a top (and right) margin
image

even with the built in fusion-dark it looks a bit too tightly packed for my taste
image

for comparison this is a system window in windows. matching the margin on all sides would be good i think. (should line up with bottom right buttons, etc.)
image

**Comment by ghost** [comment]
For me, it crashes almost every time the game is closed, but is fine otherwise. Win64 legacy portable.

**Comment by DioEgizio** [comment]
image

still doesn't seem to have the margins at the top for me

**Comment by ZekeZDev** [comment]
Thats weird

**Comment by ZekeZDev** [comment]
image
this is what it looks like on windows

**Comment by DioEgizio** [comment]
this closes https://github.com/PolyMC/PolyMC/issues/1078, so feel free to add "closes https://github.com/PolyMC/PolyMC/issues/1078" in the pr description

**Comment by ZekeZDev** [comment]
Need a solution for macos issues I also dont have a mac device for testing. If anyone would like to help contribute by testing mac for me that would be greatly appreciated.

**Comment by TayouVR** [comment]
wasn't there the idea to add the top margin as a empty extra widget with fixed height?

**Pull request closed without merging**
