### PR TITLE
Make Christmas cat last longer

### PR DESCRIPTION
**Pull request by HeyaGlitz**
The cat now lasts until January 6th, the actual end of Christmas.

### CODE REVIEW

**Comment by LennyMcLennington** [comment]
This also extends it in the lead-up to Christmas, is that intentional?

**Comment by HeyaGlitz** [comment]
Definitely not, will fix.

**Comment by LennyMcLennington** [comment]
Why not just define a separate date for the end of Christmas and check whether the current date is between those dates? Doesn't make sense to change the dates like that imo. That makes it more annoying to reason out which days it's gonna be active for.

**Comment by slendidev** [comment]
Jan 6 is not the actual end of Christmas, Jesus being born and Him being baptised are two distinct events and should be celebrated separately, also we do not know for sure when Jesus was baptised.

**Comment by HeyaGlitz** [comment]
:zzz:

**Comment by HeyaGlitz** [comment]
forgor branches

**Pull request merged**
