### PR TITLE
Link internal libraries statically

### PR DESCRIPTION
**Pull request by Scrumplex**
There is no reason to dynamically link nbt++. Let's just link it statically.

### CODE REVIEW

**Comment by d-513** [comment]
this is the only remain of dynamic linking internal libraries. If this is merged, we should be able to remove the multimc conflict from packages, right?

**Comment by Scrumplex** [comment]
Nope

**Comment by Scrumplex** [comment]
Let me elaborate: 
```
# pacman -Ql polymc-git
polymc-git /usr/
polymc-git /usr/bin/
polymc-git /usr/bin/polymc
polymc-git /usr/lib/
polymc-git /usr/lib/libLauncher_iconfix.so
polymc-git /usr/lib/libLauncher_nbt++.so
polymc-git /usr/lib/libLauncher_rainbow.so
polymc-git /usr/share/
polymc-git /usr/share/applications/
polymc-git /usr/share/applications/org.polymc.polymc.desktop
polymc-git /usr/share/icons/
polymc-git /usr/share/icons/hicolor/
polymc-git /usr/share/icons/hicolor/scalable/
polymc-git /usr/share/icons/hicolor/scalable/apps/
polymc-git /usr/share/icons/hicolor/scalable/apps/org.polymc.PolyMC.svg
polymc-git /usr/share/metainfo/
polymc-git /usr/share/metainfo/org.polymc.PolyMC.metainfo.xml
polymc-git /usr/share/polymc/
polymc-git /usr/share/polymc/jars/
polymc-git /usr/share/polymc/jars/JavaCheck.jar
polymc-git /usr/share/polymc/jars/NewLaunch.jar
```

I think this is enough explanation

**Comment by ghost** [comment]
change `libLauncher` to `libPolyMC`

**Comment by Scrumplex** [comment]
Ideally we would probably want to remove these libs. Iconfix could be irrelevant with Qt 5.12 while I still don't know what rainbow is for

**Comment by ghost** [comment]
rainbow is an adaptive text coloring thing from KGuiAddons, and iconfix removal can be put in the 5.12 PR. Though I'm still not sure if that will be merged at any point (I'm personally against it, but final decision goes to Lenny)

Also not sure why rainbow is a separate library, I can look into that later

**Comment by d-513** [comment]
can we just static link all those libraries its just junk to have them put into /usr/lib when they should be statically linked. Theres no point dynamically linking libs that dont have their own packages

**Comment by Scrumplex** [comment]
I think the initial reason for dynamically linking was licensing. MMC was Apache-2.0 and the maintainers probably didn't want to think about licensing. As we are distributing PolyMC under the terms of the GPL-3.0, we are probably able to get away with statically linking all of them.

**Comment by Scrumplex** [comment]
There we go

**Review by ghost — APPROVED** [review]

**Comment by Scrumplex** [comment]
No idea what's up with Windows. Maybe @txtsd's Win32 build will fix it magically?

**Review by d-513 — APPROVED** [review]

**Comment by txtsd** [comment]
Why is this failing on the rainbow library but only on Windows? :thinking:

**Comment by Scrumplex** [comment]
I have no clue. I just hope that your 32bit build will fix the issue magically 😅

**Comment by Scrumplex** [comment]
Rebased on develop

**Comment by txtsd** [comment]
Fingers crossed!

**Comment by Scrumplex** [comment]
Maybe it's my fault? Gonna check on this later today.

**Comment by txtsd** [comment]
Maybe you can leave rainbow as dynamically linked for now? Or we can deep dive and remove rainbow all together. I'm sure Qt can handle whatever rainbow was originally introduced to do.

**Comment by Scrumplex** [comment]
It would be nice getting this statically linked for 1.1.0 though. That way users can install MMC and PolyMC alongside each other

**Comment by ghost** [comment]
rainbow would only be unneeded if the user has kGuiAddOns installed

**Comment by txtsd** [comment]
> rainbow would only be unneeded if the user has kGuiAddOns installed

It's only used to mix colors. We can do that ourselves without a library.

**Comment by Scrumplex** [comment]
Well. Let's revert it for now and deal with it later.

**Comment by d-513** [comment]
Can we just change libLauncher to libPolyMC for now? Or package rainbow

**Comment by txtsd** [comment]
If you still want to be able to install this alongside MultiMC though, might as well rename it to libPolyMC. And we can figure rainbow out later.

**Comment by Scrumplex** [comment]
There we go. `libPolyMC_rainbow`

**Comment by LennyMcLennington** [comment]
Can't the renaming be done on another PR since it probably needs to be done regardless of whether this PR will be merged

**Comment by Scrumplex** [comment]
> Can't the renaming be done on another PR since it probably needs to be done regardless of whether this PR will be merged

rainbow is the only library left (in this PR) that's dynamically linked, so it should be fine here I guess.

Or do you see anything that blocks this PR from merging

**Comment by LennyMcLennington** [comment]
> rainbow is the only library left (in this PR) that's dynamically linked, so it should be fine here I guess.

Okay, fair enough.

**Comment by LennyMcLennington** [comment]
Is it ok to be merged now?

**Comment by Scrumplex** [comment]
> Is it ok to be merged now?

let's wait for the workflows to finish

**Comment by Scrumplex** [comment]
ready to merge!

**Pull request merged**
