### PR TITLE
fix websiteurl in curseforge modpacks

### PR DESCRIPTION
**Pull request by DioEgizio**

### CODE REVIEW

**Comment by Scrumplex** [comment]
Do we want to push this in a patch release?

**Comment by DioEgizio** [comment]
wdym this is a fix for a button not working, we had this bug for modrinth mods before, I don't think we should make a backport release just for this.

**Comment by ryanccn** [comment]
ahhh I forgot to add that to the new PR

**Review by Scrumplex — APPROVED** [review]

**Review by ryanccn — APPROVED** [review]

**Review by timoreo22 — APPROVED** [review]

**Review by d-513 — APPROVED** [review]
good

**Pull request merged**
