### PR TITLE
feat: add Big Sur style icon for macOS

### PR DESCRIPTION
**Pull request by ryanccn**

### CODE REVIEW

**Comment by Scrumplex** [comment]
Why did you change launcher/resources/pe_light/scalable/launcher.svg?

It was introduced with #370

**Comment by ryanccn** [comment]
I just ran `./genicons.sh`

**Comment by ryanccn** [comment]
weird

**Comment by DioEgizio** [comment]
Without a ICNS shouldn't it be without icon on MacOS?

**Comment by ryanccn** [comment]
> Without a ICNS shouldn't it be without icon on MacOS?

@DioEgizio there is, it's just really small for some reason

**Comment by ryanccn** [comment]
@Scrumplex fixed

**Comment by DioEgizio** [comment]
> > Without a ICNS shouldn't it be without icon on MacOS?
> 
> @DioEgizio there is, it's just really small for some reason

oh

**Review by d-513 — APPROVED** [review]

**Review by timoreo22 — APPROVED** [review]

**Comment by Scrumplex** [comment]
@ryanccn can you squash your commits? Binary files and Git don't go well and the Git history is already unneccessarily large (as in size in bytes)

**Comment by d-513** [comment]
we can squash in merge (arrow next to merge pull). Now approve it.

**Comment by Scrumplex** [comment]
> we can squash in merge (arrow next to merge pull). Now approve it.

GitHub squash is cringe, because it overrides the GPG signature with GitHub's key.

**Comment by d-513** [comment]
scrumplex moment

**Comment by ryanccn** [comment]
done @Scrumplex

**Comment by Scrumplex** [comment]
How does this work? Don't we need to copy the icons to the .app bundle or something?

**Comment by DioEgizio** [comment]
wdym it's like before, he just updated the icns that gets bundled

**Comment by Scrumplex** [comment]
oh, I see. It looked like the .icns was deleted, but it just got considerably smaller. Okay. LGTM

**Review by Scrumplex — APPROVED** [review]

**Pull request merged**
