### PR TITLE
Option to close PolyMC after launch

### LINKED ISSUE #70: Add option to close PolyMC after launching the game [multimc suggestion]
### Role

playing minecrat

### Suggestion

Add a setting to close MultiMC after launching the game

### Benefit

similar to how the default minecraft launcher works close PolyMC after launching the game. may be benificial to low end computer's or planned arm release.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

From issue [#3406](https://github.com/MultiMC/Launcher/issues/3406) for multimc.

### PR DESCRIPTION
**Pull request by ghost**
Closes: #70 

Questions:
- How should I go about "processing" stdout?
- What function is used to close the window, but not the application? I believe it's `QMainWindow::hide()`
- What settings tab should this be in? I'm thinking either `Launcher/Features` or `Minecraft`.

Todo:
- [x] When a line containing "LWJGL Version" (i.e. right before the Minecraft window opens) is logged, hide the window
- [x] Put stuff in the UI

### CODE REVIEW

**Comment by redstrate** [comment]
* There are functions in ‘QProcess’ to read stdout like any other IO device, it seems while skimming ‘launcher/launch’ multimc might wrap over this behavior though.

* Yes that should be the right way, but I would be wary about doing this as it could easily zombie the process if we have no way to reopen the window. 

* I think it should be in ‘Minecraft’ just so it makes more sense in the instance specific options (that’s where the big “open global settings” button leads to.

**Comment by ghost** [comment]
I know how to *get* stdout, I just don't know where the function should even go. 

Also, I'd like to "close" the window the same way it's closed when you exit the app, i.e. the X button on DEs or a quit command from a WM

**Comment by ghost** [comment]
Finished everything up.

Caveats:
- "Setting user" doesn't apply to early versions (pre-1.0), and in recent versions is printed around 5 seconds before the window opens.

**Comment by ghost** [comment]
The code probably doesn't need a review but I have been known to make some serious spaghetti

**Pull request merged**
