### PR TITLE
Show the current branch rather than "custom" in version string

### LINKED ISSUE #159: "remove the -custom"
### Role

I play modded mc

### Suggestion

remove the -custom thingy in title as every build is custom

### Benefit

why not

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Schermata 2022-02-12 alle 17 10 44

### PR DESCRIPTION
**Pull request by Scrumplex**
Closes #159

My local build of this branch

(my branch is called `custom-be-gone`)

### CODE REVIEW

**Comment by DioEgizio** [comment]
cool

**Comment by LennyMcLennington** [comment]
Shows as -unknown with gh actions. This isn't important for debug builds but if you want to use GH actions instead of jenkins for release workflow then this should be rectified in some way.

**Comment by Scrumplex** [comment]
> Shows as -unknown with gh actions. 

Oh, let me see if I can fix that

**Review by timoreo22 — APPROVED** [review]
Looks good !

**Review by d-513 — COMMENTED** [review]
Could we have a suffix option for this? So that its easier to work out which package user is using from screenshots, like `-appimage`, etc

**Comment by Scrumplex** [comment]
> Could we have a suffix option for this?

I don't know if we want this as part of the version string. Maybe we can add a separate property that can be set at build-time, that specifies the distribution method.

```
$ cmake ... -DLauncher_DISTRIBUTION=appimage
```

Then we just need to put this value into a few places of the launcher (log files, about page). But that's def. a new PR.

**Review by d-513 — APPROVED** [review]

**Review by txtsd — APPROVED** [review]
LGTM!

**Pull request merged**
