### PR TITLE
fix appimage not having imageformats

### PR DESCRIPTION
**Pull request by DioEgizio**
fixes stuff like the iris icon

### CODE REVIEW

**Comment by Scrumplex** [comment]
do we need all those ppas?

**Comment by txtsd** [comment]
Yea why gpg and ffmpeg4?

**Comment by DioEgizio** [comment]
> do we need all those ppas?

yep



> Yea why gpg and ffmpeg4?

We need them b/c dependencies

**Comment by txtsd** [comment]
Rebase pls

**Comment by DioEgizio** [comment]
wdym it's not conflicting

**Comment by txtsd** [comment]
> wdym it's not conflicting

For the builds to pass, not for conflicts.

**Comment by DioEgizio** [comment]
oh, yeah now I rebased btw

**Review by Scrumplex — APPROVED** [review]

**Review by txtsd — APPROVED** [review]

**Review by flowln — APPROVED** [review]

**Pull request merged**
