### PR TITLE
Update bug_report.yml to use latest version as the version suggestion

### PR DESCRIPTION
**Pull request by Un1q32**

### CODE REVIEW

**Review by flowln — APPROVED** [review]
kinda sad we need to manually update this :(
@ people that do version bump PRs, remember this !!1!

**Comment by DioEgizio** [comment]
i mean, that's just an example, idk if we need to update it every time

**Comment by Un1q32** [comment]
> i mean, that's just an example, idk if we need to update it every time

we dont NEED to but it would look slightly nicer

**Review by txtsd — APPROVED** [review]

**Comment by flowln** [comment]
@OldWorldOrdr can you update this to 1.3.2? Then we ~force~ ask nicely another maintainer to approve it before 1.4.0, and then update as we go :)

**Comment by Un1q32** [comment]
@flowln done

**Review by ZekeZDev — APPROVED** [review]

**Pull request merged**
