### PR TITLE
Draft: Bump Qt requirement to 5.15

### PR DESCRIPTION
**Pull request by Scrumplex**
I think we should migrate to Qt 6 in the future. But before doing that we need to remove references to deprecated stuff. I haven't tested everything yet, so can't give any guarantees.

### CODE REVIEW

**Comment by ghost** [comment]
We should at the very least allow this to be built on Qt 6.

Defaulting to it or requiring it is a bad idea. Gentoo and some other distros don't have 6 yet

**Comment by Scrumplex** [comment]
Yeah I already assumed that defaulting to Qt 6 would be bad

**Comment by redstrate** [comment]
I'm also supporting this (as an option) :-)

For example, many projects are using a cmake option like `BUILD_WITH_QT6`. The main reason is that many Qt5 themes including the default KDE one are not updated to Qt6 yet (and probably wont for another few months) and this has already caused a fiasco with another popular Qt application - qbittorrent (that's why `qbittorrent-qt5` now exists on the AUR lol). Forcing Qt6 at the moment is not really needed unless you *really* need a Qt6 feature.

**Comment by Scrumplex** [comment]
There is a Qt6 "qt5compat" component. I think that one also allows themes to work?

**Comment by redstrate** [comment]
> There is a Qt6 "qt5compat" component. I think that one also allows themes to work?

That only deals with the deprecated APIs in Qt6 (it unfortunately doesnt have anything to do with themes). Themes should be able to port over quite easily to Qt6 it's just that it's too new for anyone to build against it yet :-/

**Comment by Scrumplex** [comment]
Oh I just checked, Fusion is indeed ugly :D

**Comment by ghost** [comment]
I'll test this in a bit. If everything works as expected, and it compiles, then we're good. I'm not sure what all to test though

**Comment by Scrumplex** [comment]
So there is a small issue here: I did all the refactoring on Qt 5.15.2. Some things I have changed were only deprecated since Qt 5.15. So right now this is incompatible with 5.12. Maybe we just wanna bump Qt requirement to 5.15? 


Doing this would only support the following platforms:

- Alpine 3.13 or later
- Arch
- Debian 11 (bullseye) or later
- Fedora 33 or later
- macOS 10.13 (High Sierra, released 2017) or later
- NixOS 21.05 or later
- openSUSE Tumbleweed
- Ubuntu 21.04 or later
- Void
- Windows 7 or later

I feel like it's probably fine. The only missing platform is Ubuntu 20.04. But I am sure we can make up for that using Flatpak (or maybe a Snap?)

**Comment by ghost** [comment]
As gman was saying, 5.9 should realistically be the oldest version we target. If anything doesn't work on 5.9 or 5.12 it shouldn't be added.

I'm not entirely sure how possible it is to support all the way from 5.9 to 6.2 Maybe we could have an `ENABLE_QT_5_9` build flag which uses those methods deprecated later on.

**Comment by Scrumplex** [comment]
Depends on #127

**Comment by Scrumplex** [comment]
I am going to close this one for now. But we might use this in the future.

**Pull request closed without merging**
