### PR TITLE
switch to NCoC (No Code of Conduct)

### PR DESCRIPTION
**Pull request by ghost**
This is a general discussion/forum about changes to the code of conduct.

I would like to switch to NCoC but many others want to simply modify the current one to be less bad, and this PR can be changed to modification of the current CoC

### CODE REVIEW

**Comment by timoreo22** [comment]
So on the previous pr #178 a lot of pepole were okay with the change, i don't think we should revert it,  i'll keep this pr open for discussion

**Comment by ghost** [comment]
> So on the previous pr #178 a lot of pepole were okay with the change, i don't think we should revert it,  i'll keep this pr open for discussion

I was not okay with having a CoC at all, and even if I was the Contributor Covenant is an extremely flawed implementation of a CoC that provides little basis for any type of rule outside of "do NOT be mean". It contains vague statements that don't accomplish any more than common sense would (woah, don't be rude? I can't believe it!)

This isn't even to mention the "everyone, including..." junk that just sounds like a "hey guys look we care about group X" virtue signal.

Because of this, the NCoC just makes much more sense to me.

**Comment by ghost** [comment]
I'd also like to mention the lack of a proper formal discussion. We can't just blindly implement changes that a portion of our users may not be okay with (me included).

**Comment by Zetvue** [comment]
Find another CoC then. I disagree with this change.
**Rules exist.**

**Comment by ZekeZDev** [comment]
I am going to close this pull as it serves no benefit. discussion can be continued in the github discussion section. There is 7 people to 1 on the post I think its fsir to say this is voted on.

**Comment by ghost** [comment]
If you aren't even going to allow **basic** discussion over a major developmental change that not everyone agrees with (and no, 7 people is not "everyone"), then you are not fit for " maintaning" this project.

This is exactly what I was talking about. You are making changes against the fundamental goal of what I wanted PolyMC to be and creating exactly what I never wanted out of this project.

Quit merging big changes like this without discussing properly with all developers and contributors.

**Pull request closed without merging**
