### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by technoalli3**
I see you accidentally closed the pull request. You gotta click the green one that says "yes".

### CODE REVIEW

**Review by Madeleaan — APPROVED** [review]

**Review by Weredime — APPROVED** [review]

**Review by Weredime — APPROVED** [review]

**Review by Weredime — APPROVED** [review]

**Review by Weredime — APPROVED** [review]

**Review by Weredime — APPROVED** [review]

**Review by Weredime — APPROVED** [review]

**Review by Weredime — APPROVED** [review]

**Review by zach7676 — APPROVED** [review]
looks good

**Review by Astralchroma — APPROVED** [review]

**Comment by Weredime** [comment]
Sorry github's being a bit broken over here

**Review by sunglocto — APPROVED** [review]
yah

**Review by ghost — APPROVED** [review]

**Review by PinkGoosik — APPROVED** [review]

**Review by justastranger — APPROVED** [review]

**Review by DuckyBlender — APPROVED** [review]

**Review by ooliver1 — APPROVED** [review]

**Review by ConfuSomu — APPROVED** [review]
perfect

**Review by MaeIsBad — APPROVED** [review]

**Review by tuxcrafting — APPROVED** [review]
Seems good

**Pull request closed without merging**
