### PR TITLE
Bump to 1.3.2

### PR DESCRIPTION
**Pull request by Scrumplex**
This should not be merged into develop.

### CODE REVIEW

**Comment by d-513** [comment]
but shouldnt we bump develop too always

**Comment by Scrumplex** [comment]
See #782 :D

**Comment by flowln** [comment]
Bump the issues one too, as in #729 :)

**Review by d-513 — APPROVED** [review]

**Review by timoreo22 — APPROVED** [review]

**Comment by Scrumplex** [comment]
> Bump the issues one too, as in #729 :)

This is merged into release-1.3.x so it doesn't reaallly matter

**Comment by flowln** [comment]
> This is merged into release-1.3.x so it doesn't reaallly matter

ok .-.
but do it for 1.4.0 then :D

**Review by flowln — APPROVED** [review]

**Pull request merged**
