### PR TITLE
Run markdownlint on the markdown files

### PR DESCRIPTION
**Pull request by txtsd**
One rule per commit

I've added the config to run it in the last commit. Let me know if it's unnecessary and I'll remove it.

There are still some suggestions that show when running `markdownlint .` These are edge cases and would ideally be ignored. I'd like help with ignoring them specifically without adding comments to the markdown files themselves.

### CODE REVIEW

**Comment by txtsd** [comment]
I guess I need to add those new files to CI's ignore list

**Comment by txtsd** [comment]
Strange

**Review by flowln — APPROVED** [review]

**Review by Scrumplex — APPROVED** [review]
Looks good!

**Comment by txtsd** [comment]
Conflicts have been resolved.

**Review by timoreo22 — APPROVED** [review]

**Pull request merged**
