### PR TITLE
Rewrite polymc.6 in scdoc, build, and install it

### LINKED ISSUE #844: Re-write the man page in a format which will actually render correctly in a man-page viewer.
### Role

I read man pages.

### Suggestion

Either provide a man page in raw man troff, mdocml or probably preferrably scdoc format (which then gets converted at build time to the style of troff which man consumes). Currently it's some form of markdown.

### Benefit

When opening the man page it will look like a man page and not like I have accidentally opened a text file, it will also be rendered correctly.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Let me know which of the 3 options you would prefer and I will be happy to send a PR implementing it (unless it's the first option in which case I will not send a PR and will be sad).

I can provide the following benefits/drawbacks of using each format:

- Sticking with the current format
  - Benefits:
    - You don't have to do anything. It is simple to maintain. You already know the syntax (presumably).
    - Github renders this format for you nicely in its UI so it is readable when browsing the repository.
  - Drawbacks:
    - This is not the format man pages are written in and it doesn't look correct on linux systems.
    - I will be sad.
- Raw man troff format:
  - Benefits:
    - The man page will look correct and render correctly on all linux and also other unix and unix-like systems.
    - You will actually get to see the styling information in man page viewers.
    - I will be happy.
  - Drawbacks:
    - While I can happily do it as I know the format, the raw man troff format is horrific. Example here: https://the-tk.com/cgit/hktool/tree/hktool.1 This may not be the most maintainable as most people don't know troff.
- mdocml (http://mandoc.bsd.lv/):
  - Benefits:
    - The man page will look correct and render correctly on most linux and many other unix and unix-like systems as long as they support the mdocml format.
    - You will actually get to see the styling information in man page viewers.
    - It is a bit easier to write than the pure man troff format.
    - I will be happy.
  - Drawbacks:
    - While I can happily do it as I know the format, the mdocml format is a bit meh and not very intuitive either. Example here: https://raw.githubusercontent.com/openbsd/src/master/share/man/man1/intro.1 This may not be the most maintainable as most people don't know mdocml.
- scdoc (https://drewdevault.com/2018/05/13/scdoc.html):
  - Benefits:
    - The man page will look correct and render correctly on all linux and other unix and unix-like systems as long as the package is built on a system which contains a copy of the very portable and easily built scdoc binary.
    - You will actually get to see the styling information in man page viewers.
    - Github renders this format for you nicely in its UI so it is readable when browsing the repository. (https://github.com/swaywm/sway/blob/master/sway/sway.1.scd)
    - It is as easy to write as the current format and will actually not require much of a change.
    - I will be happy.
  - Drawbacks:
    - Your build will (optionally) depend on an installed copy of scdoc, that being said, scdoc is packaged in an awful lot of places (https://repology.org/project/scdoc/versions).

### PR DESCRIPTION
**Pull request by EliteTK**
I don't really know anything about CMake so this may be the wrong way to go about things.

This would close #844.

### CODE REVIEW

**Comment by Scrumplex** [comment]
Looks pretty good. The only thing I would probably like to change is *where* the `scdoc` stuff is handled. 

I prepared the following patch, which would move most of that stuff to program_info. Then we just need to run `install()` in the root `CMakeFiles.txt`. An alternative would be moving documentation to a new subdirectory and by extension CMake module, but I am not sure if we will ever expand the documentation there so that might be overkill

```patch
From 67bca41cdfc2d644ac54e531e27bdeb6fb445dec Mon Sep 17 00:00:00 2001
From: Sefa Eyeoglu <contact@scrumplex.net>
Date: Sun, 26 Jun 2022 21:46:29 +0200
Subject: [PATCH 2/2] refactor: move scdoc generation to program_info

---
 CMakeLists.txt              | 17 ++---------------
 program_info/CMakeLists.txt | 24 ++++++++++++++++++++++--
 2 files changed, 24 insertions(+), 17 deletions(-)

diff --git a/CMakeLists.txt b/CMakeLists.txt
index 4797dc78..8a4b413e 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -239,21 +239,8 @@ elseif(UNIX)
     install(FILES ${CMAKE_CURRENT_BINARY_DIR}/${Launcher_MetaInfo} DESTINATION ${LAUNCHER_METAINFO_DEST_DIR})
     install(FILES ${CMAKE_CURRENT_SOURCE_DIR}/${Launcher_SVG} DESTINATION ${LAUNCHER_ICON_DEST_DIR})
 
-    find_package(PkgConfig)
-    if(${PkgConfig_FOUND})
-        pkg_search_module(SCDOC scdoc)
-        if(${SCDOC_FOUND})
-            pkg_get_variable(SCDOC_SCDOC scdoc scdoc)
-            set(in_scd ${CMAKE_CURRENT_SOURCE_DIR}/${Launcher_ManPageSource})
-            set(out_man ${CMAKE_CURRENT_BINARY_DIR}/${Launcher_ManPage})
-            add_custom_command(
-                DEPENDS ${in_scd}
-                OUTPUT ${out_man}
-                COMMAND ${SCDOC_SCDOC} <${in_scd} >${out_man}
-            )
-            add_custom_target(man ALL DEPENDS ${out_man})
-            install(FILES ${CMAKE_CURRENT_BINARY_DIR}/${Launcher_ManPage} DESTINATION ${LAUNCHER_MAN_DEST_DIR})
-        endif()
+    if(Launcher_ManPage)
+        install(FILES ${CMAKE_CURRENT_BINARY_DIR}/${Launcher_ManPage} DESTINATION ${LAUNCHER_MAN_DEST_DIR})
     endif()
 
     # Install basic runner script if component "portable" is selected
diff --git a/program_info/CMakeLists.txt b/program_info/CMakeLists.txt
index 2f988225..b1ba89df 100644
--- a/program_info/CMakeLists.txt
+++ b/program_info/CMakeLists.txt
@@ -1,3 +1,13 @@
+if(UNIX)
+    find_package(PkgConfig)
+    if(PkgConfig_FOUND)
+        pkg_search_module(SCDOC scdoc)
+        if(SCDOC_FOUND)
+            pkg_get_variable(SCDOC_SCDOC scdoc scdoc)
+        endif()
+    endif()
+endif()
+
 set(Launcher_CommonName "PolyMC")
 
 set(Launcher_Copyright "PolyMC Contributors\\n© 2012-2021 MultiMC Contributors")
@@ -12,8 +22,6 @@ set(Launcher_DesktopFileName "org.polymc.PolyMC.desktop" PARENT_SCOPE)
 
 set(Launcher_Desktop "program_info/org.polymc.PolyMC.desktop" PARENT_SCOPE)
 set(Launcher_MetaInfo "program_info/org.polymc.PolyMC.metainfo.xml" PARENT_SCOPE)
-set(Launcher_ManPageSource "program_info/polymc.6.scd" PARENT_SCOPE)
-set(Launcher_ManPage "program_info/polymc.6" PARENT_SCOPE)
 set(Launcher_SVG "program_info/org.polymc.PolyMC.svg" PARENT_SCOPE)
 set(Launcher_Branding_ICNS "program_info/polymc.icns" PARENT_SCOPE)
 set(Launcher_Branding_ICO "program_info/polymc.ico")
@@ -29,3 +37,15 @@ configure_file(polymc.rc.in polymc.rc @ONLY)
 configure_file(polymc.manifest.in polymc.manifest @ONLY)
 configure_file(polymc.ico polymc.ico COPYONLY)
 configure_file(win_install.nsi.in win_install.nsi @ONLY)
+
+if(SCDOC_FOUND)
+    set(in_scd "${CMAKE_CURRENT_SOURCE_DIR}/polymc.6.scd")
+    set(out_man "${CMAKE_CURRENT_BINARY_DIR}/polymc.6")
+    add_custom_command(
+        DEPENDS "${in_scd}"
+        OUTPUT "${out_man}"
+        COMMAND ${SCDOC_SCDOC} < "${in_scd}" > "${out_man}"
+    )
+    add_custom_target(man ALL DEPENDS ${out_man})
+    set(Launcher_ManPage "program_info/polymc.6" PARENT_SCOPE)
+endif()
-- 
2.36.1


```

**Comment by EliteTK** [comment]
Apologies for the delay in replying. I was at a company event and then I had to deal with COVID.

@Scrumplex I have amended the commit in the way you requested. I have marked the PR as ready to review.

**Comment by txtsd** [comment]
What's the benefit of using `scdoc`?

**Comment by EliteTK** [comment]
@txtsd I think #844 covers this topic quite well.

**Comment by txtsd** [comment]
Excellent!

**Comment by txtsd** [comment]
It skips building the manpage if `scdoc` does not exist on the system. Is this how we want it to behave?

**Review by txtsd — APPROVED** [review]
The man page looks excellent now though!

**Comment by EliteTK** [comment]
@txtsd well without scdoc it could dump the file in /usr/share/doc/polymc but I think given the ubiquity of scdoc it may be easier to just leave it as it is and instead document the fact that distributions and people compiling themselves should use scdoc to build the man page.

**Comment by txtsd** [comment]
AUR and MPR packages will need to add `scdoc` as `makedepends` once this is merged.
CC @Scrumplex @dada513

**Review by Scrumplex — APPROVED** [review]

**Review by flowln — APPROVED** [review]

**Comment by Scrumplex** [comment]
Thanks! I have added `scdoc` as a build-time dependency on the AUR

**Pull request merged**
