### PR TITLE
Remove Mojang account UI

### PR DESCRIPTION
**Pull request by Scrumplex**
- Removes `Add Mojang` action
- Removes Mojang login dialog
- Removes `Can migrate?` column in accounts list
- Shows MSA accounts as `MSA` instead of ugly `Msa`

Users on Discord reported, that newly logging in doesn't work anymore. This does not remove any code that would break authentication for already logged in accounts. So this is not a breaking change

### CODE REVIEW

**Comment by glowiak** [comment]
But what if someone still has a moejang account?

**Comment by glowiak** [comment]
And he's not logged in

**Comment by tonyaellie** [comment]
then you probably need to migrate your account

**Comment by Scrumplex** [comment]
I wrote it in the description of the PR:

> Users on Discord reported, that newly logging in doesn't work anymore.

**Comment by d-513** [comment]
it does actually work for me still. Seems that it's account-based, or some accounts are marked when seeing the alert in launcher.
Either way let's do this once Yggdrasil stops working completely. I can still log in and out.

**Comment by Scrumplex** [comment]
Hmm interesting. I might extend this PR then to remove Mojang accounts completely

**Comment by d-513** [comment]
Yeah do that and merge once Yggdrasil is completely dead.
Let's support mojang until it isn't possible to

**Comment by obj-obj** [comment]
It also still works for me

**Comment by Scrumplex** [comment]
(rebase)

**Comment by Scrumplex** [comment]
As far as I can tell, Mojang auth is now gone for good?

**Comment by Scrumplex** [comment]
See #354 instead

**Comment by d-513** [comment]
I guess close this PR?

**Pull request closed without merging**
