### PR TITLE
Switch to new versioning scheme

### PR DESCRIPTION
**Pull request by Scrumplex**
```
The new versioning system is based on the versioning system used by the
GNOME Foundation for the GNOME desktop.

We are dropping the "major version" as defined by SemVer and move to a
version number with a most and least significant number.

The most significant number must be incremented, if there are new
features or significant changes since last major release.

Otherwise, the least significant number must be incremented, if there
are only minor changes since the last release. New features or
significant changes mustn't be introduced by a bump of the least
significant number.

If a minor change would introduce small user-facing changes (like a
message-box or slight UI changes), it could still be classified as a
minor change.
At the end of the day, a human shall decide, if a change is minor or
significant, as there is no clear line that would separate a "minor" and
a "significant" change in a GUI-application.

Definitions:

feature: New user-facing functionality
significant change: Something that changes user-facing behavior
minor change: Something that fixes unexpected behavior
```

### CODE REVIEW

**Comment by txtsd** [comment]
Screenshot 2022-07-30 at 10-25-11 Switch to new versioning scheme by Scrumplex · Pull Request #992 · PolyMC_PolyMC

TODOs are love. TODOs are life.
:laughing:

**Comment by Scrumplex** [comment]
Now with 100% less TODOs, and 100% more useful commit descriptions

**Comment by BeansBeefBroccoli** [comment]
PolyMC 5.0

- Removed Hotfixes

**Review by flowln — APPROVED** [review]
we'll be in PolyMC 5 and we haven't even finished the electron rewrite from v2 :pensive:

**Review by timoreo22 — APPROVED** [review]

**Comment by DioEgizio** [comment]
image
version in macos is a bit weird

which in the updater means
image

**Comment by DioEgizio** [comment]
looks fine if i change it manually in the info.plist

**Comment by DioEgizio** [comment]
https://github.com/PolyMC/PolyMC/blob/c375e7b4dfbdf7c201c42a70c96a1b2afdc34552/CMakeLists.txt#L229
https://github.com/PolyMC/PolyMC/blob/c375e7b4dfbdf7c201c42a70c96a1b2afdc34552/CMakeLists.txt#L230
https://github.com/PolyMC/PolyMC/blob/c375e7b4dfbdf7c201c42a70c96a1b2afdc34552/CMakeLists.txt#L231

i think you have to change there removing ${Launcher_VERSION_HOTFIX}")

**Comment by DioEgizio** [comment]
yep now looks fine

**Pull request merged**
