### PR TITLE
Revert "Move classpath definition into NewLaunch itself"

### LINKED ISSUE #1101: Bug when trying to start forge instance: No file detector is enabled
### Operating System

Linux

### Version of PolyMC

$ polymc --version
Version 5.0-develop
Git ba3ac85356802130842c6ad6fb0c09b6f3c672c5

### Version of Qt

Qt 6.3.1

### Description of bug

Can't start any forge instance.

### Steps to reproduce

- Create a new instance
- Install recommended forge version
- Launch that instance
- The instance will fail to start with `No file detector is enabled`
The logs can be found here: https://mclo.gs/O60jjEW

Also is reproduced with any already installed forge instances 

### Suspected cause

_No response_

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### PR DESCRIPTION
**Pull request by Scrumplex**
Reverts PolyMC/PolyMC#1067

Closes #1101

I will see if I can get this to work later

### CODE REVIEW

**Comment by Scrumplex** [comment]
Oh right. GitHub doesn't allow me to change the commit message when creating a revert PR

**Review by timoreo22 — APPROVED** [review]
Classpath epicness not being epic

**Review by flowln — APPROVED** [review]
rip

**Comment by DioEgizio** [comment]
Merge?

**Pull request merged**
