### PR TITLE
backport some stuff for 1.2.2

### PR DESCRIPTION
**Pull request by DioEgizio**

### CODE REVIEW

**Comment by Scrumplex** [comment]
This is probably gonna make our git history ugly again like with #381

**Comment by DioEgizio** [comment]
yeah but i think it's ok since just 3 commits

**Review by d-513 — APPROVED** [review]

**Comment by d-513** [comment]
can we figure out a way of doing this without ugly commit history

**Comment by Med1cinal** [comment]
git rebase -i HEAD~3

**Comment by Scrumplex** [comment]
> git rebase -i HEAD~3

We can't really rebase develop onto stable, without breaking people's local clones of the repo

**Review by timoreo22 — APPROVED** [review]

**Review by Scrumplex — APPROVED** [review]

**Pull request merged**
