### PR TITLE
downgrade comment on pr bot to fix it

### PR DESCRIPTION
**Pull request by DioEgizio**
probably

(haven't tested it)

### CODE REVIEW

**Comment by LennyMcLennington** [comment]
test it then

**Comment by DioEgizio** [comment]
How though, I'd need to do a pr from another repository targeting that branch

**Comment by DioEgizio** [comment]
probably the easiest way to test it is merging this and seeing if it fixed

**Comment by kthchew** [comment]
Can't you (or someone else) open a PR against your own fork to test it?

**Comment by DioEgizio** [comment]
I can't because the bug only happens when doing a pr from a fork to the main repo

**Comment by txtsd** [comment]
Have someone fork your fork, then submit a PR to your fork. But this will need to be merged in your fork's develop branch to test it.

**Comment by DioEgizio** [comment]
Actually on my fix-pr-comment branch

**Comment by Scrumplex** [comment]
Maybe we should just remove it. I don't think it has much value.

**Comment by txtsd** [comment]
> Maybe we should just remove it. I don't think it has much value.

Yea, PRs have the Checks tab where one can download artifacts from. Might as well get rid of it since it isn't working as intended.

**Comment by DioEgizio** [comment]
I mean we can always try to merge this and see if it works 😄

**Comment by flowln** [comment]
Will this still be done? Seems like people are going more towards #633 with the removal instead o.o

**Comment by DioEgizio** [comment]
Idk, but we could try this and then trying the removal in a worst-case scenario

**Comment by DioEgizio** [comment]
🦀

**Pull request closed without merging**
