### PR TITLE
Chocolatey package

### LINKED ISSUE #165: Chocolatey support
### Role

i install most software via chocolatey on windows

### Suggestion

add polymc to chocolatey https://chocolatey.org/

### Benefit

people can install polymc via chocolatey

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

_No response_

### PR DESCRIPTION
**Pull request by txtsd**
Okay so, this is based on the [multimc chocolatey package](https://community.chocolatey.org/packages/multimc). [Source is here](https://github.com/sorashi/chocolatey-packages/tree/master/manual/multimc).

I can add more `<owners>`. It needs to be the username on [community.chocolatey.org](https://community.chocolatey.org).

JRE 8 and 17 are set as dependencies so users don't have to worry about installing java by themselves. We use [temurin](https://adoptium.net).

We currently use `C:\Tools\PolyMC` as the install directory. This is how multimc does it too, because choco's [get-toolslocation](https://docs.chocolatey.org/en-us/create/functions/get-toolslocation) returns `C:\Tools`.
> Gets the top level location for tools/software installed outside of package folders.

Package folders like `C:\Program Files (x86)` and `C:\ProgramData\chocolatey\lib\polymc\tools` are flagged as read-only so PolyMC can't write to them and refuses to launch. If we default to using `%APPDATA%` for the Windows builds, we can install to a proper location and avoid this problem.

Currently, instance folders are deleted if PolyMC is uninstalled via choco since the instance folder is inside the install folder. The user is warned they will lose their instances when uninstalling. We can avoid this scenario if we address the previous point.

The package manually creates Start Menu and Desktop shortcuts during install.

The PNG icon is required by chocolatey. It has been `pngcrush`ed.

The README is severely lacking. Ideas for content are welcome.

~~If this can be merged before 1.1.0, I'd like to change the develop links to stable first. Once it's merged, I'll `choco push` the package. Making fixes without bumping the version is frowned on, and I'd like to keep the package version in sync with the PolyMC version.~~

We could add a workflow to automatically push new versions, but I'd like to use the `<releaseNotes>` key from the next version onward, so I'll push manually.

Closes #165

### CODE REVIEW

**Comment by txtsd** [comment]
Package has been submitted. It is now pending mod approval.
https://community.chocolatey.org/packages/polymc

**Review by ZekeZDev — APPROVED** [review]
Looks good ill approve this so its ready once its accepted

**Review by Scrumplex — APPROVED** [review]

**Review by timoreo22 — APPROVED** [review]

**Comment by txtsd** [comment]
Do we want this in the main repo, or should this be in a different repo?

**Comment by Scrumplex** [comment]
I think it would be better to leave packaging out of the main repo.

**Comment by txtsd** [comment]
Okay I'll make a separate repo for this.

**Comment by txtsd** [comment]
Now featured in [PolyMC/chocolatey](https://github.com/PolyMC/chocolatey).

**Pull request closed without merging**
