### PR TITLE
Remove Mojang Auth for good (or bad :c)

### PR DESCRIPTION
**Pull request by Scrumplex**
Succeeds #283

### CODE REVIEW

**Comment by sdarkwell** [comment]
**Hello!**

Mojang logins still appear to be valid.

I just used a clean copy of PolyMC v1.1.0-9f8983b5 to log into my Mojang account, start Minecraft, and join a brand new local Minecraft server that I spun up in the background.

**Thank you so much and be well!**

**Comment by d-513** [comment]
Seems to indeed be done in batches.

**Comment by RuinTD** [comment]
Maybe the "Add Microsoft" button should just say "Add Account" or "Add Online"?

**Comment by TheCodex6824** [comment]
Mojang auth doesn't seem to be completely dead for me, despite my account appearing "locked". At least for me, Yggdrasil succeeds but then the ~~other auth endpoints seem to reject all auth tokens, even after freshly logging in~~ Minecraft-specific endpoints all return 403 forbidden, including the profile endpoint.

~~There is an annoying part - since auth tokens get rejected you have to enter your password every time (or save it to disk, which has problems of its own), but it works.~~

~~So tl;dr Mojang authentication is kinda dead, would take some refactoring to support (and be a bit annoying sometimes), but is possible (for now).~~

Other than that, some countries like South Korea theoretically are not eligible to migrate yet, so merging this would probably be premature anyway.

Edit: Turns out I was being stupid and auth tokens still work. However, it also seems that in addition to the profile endpoint, the skin change endpoints do ***not*** work.

**Comment by ZekeZDev** [comment]
I think we add this for 1.2.0 and allow for downloading of older releases on the website. (There is already code for older releases just needs to be implemented fully).

**Review by ZekeZDev — APPROVED** [review]

**Comment by d-513** [comment]
We could also implement @TheCodex6824’s hacks to get the auth still working. I wish I hadn’t migrated so soon

**Comment by Scrumplex** [comment]
Let's merge this for the next release cycle.

**Review by d-513 — APPROVED** [review]

**Comment by d-513** [comment]
do we need this? since Mojang now works properly for everyone because of the awesome pr

**Comment by Scrumplex** [comment]
The Mojank endpoints we use there will eventually stop working I assume. So this will be needed eventually

**Comment by LennyMcLennington** [comment]
Reopen it when it's actually needed

**Comment by DioEgizio** [comment]
Mojang decided to completely 🦀 mojang accounts now. Ig it's time to rebase this D:

**Comment by Scrumplex** [comment]
Hello darkness my old friend

**Comment by TheCodex6824** [comment]
I'm going to investigate to see if I can find a new workaround, but I'll admit it's not looking too good for Mojang accounts right now :cry:

Edit: other thing to consider is that launching the game is still fine, so people can play on offline mode servers. At this point though, I'm not sure it's worth keeping Mojang account support around for that in PolyMC

**Review by LennyMcLennington — CHANGES_REQUESTED** [review]
As long as Mojang accounts can still be signed into, there's no point in removing support for signing into them. Minecraft isn't *just* about online servers, and people who choose to not go along with Microsoft's bullshit should still be able to sign into their account to play offline.

**Comment by TheCodex6824** [comment]
> As long as Mojang accounts can still be signed into, there's no point in removing support for signing into them. Minecraft isn't _just_ about online servers, and people who choose to not go along with Microsoft's bullshit should still be able to sign into their account to play offline.

It might be worth keeping it in then, but there should probably be a message popup at some point (maybe when adding a Mojang account or launching an instance with it the first time) that explains that multiplayer authentication won't work. The error message when trying multiplayer gives the impression that it is a temporary failure and doesn't reference migration being the issue at all.

**Comment by txtsd** [comment]
> As long as Mojang accounts can still be signed into, there's no point in removing support for signing into them. Minecraft isn't _just_ about online servers, and people who choose to not go along with Microsoft's bullshit should still be able to sign into their account to play offline.

I feel this way too.

**Comment by sTiKyt** [comment]
Don't? I have lots of friends who still use Mojang accounts cuz they are against Microsoft, and they'd simply pirate or quit the game if Mojang accounts weren't an option anymore, thanks.

**Comment by sTiKyt** [comment]
> As long as Mojang accounts can still be signed into, there's no point in removing support for signing into them. Minecraft isn't _just_ about online servers, and people who choose to not go along with Microsoft's bullshit should still be able to sign into their account to play offline.

I've got online mode set to true on my server and my friends with Mojang accounts login without any issues

**Comment by Scrumplex** [comment]
> I've got online mode set to true on my server and my friends with Mojang accounts login without any issues

Can you confirm that they can *still* join? We heard from many people that they can't join anymore.

**Comment by sTiKyt** [comment]
> > I've got online mode set to true on my server and my friends with Mojang accounts login without any issues
> 
> Can you confirm that they can _still_ join? We heard from many people that they can't join anymore.

My friend is loading into game to check right now, i wasn't home for the last 3 or so days so maybe we just missed it, wait please i'll let you know

**Comment by sTiKyt** [comment]
> > > I've got online mode set to true on my server and my friends with Mojang accounts login without any issues
> > 
> > 
> > Can you confirm that they can _still_ join? We heard from many people that they can't join anymore.
> 
> My friend is loading into game to check right now, i wasn't home for the last 3 or so days so maybe we just missed it, wait please i'll let you know

Okay, my statement above was false, seems like it died for him too... That's very unfortunate, I'll just hope some mod will fix that for some people

Still, I believe Poly MC should keep Mojang as an option because it would let many people download, install and update Mod packs such as FTB in a comfortable way, even if servers themselves are Offline mode

**Comment by LennyMcLennington** [comment]
This shouldn't be on *any* milestone unless mojang accounts literally can't be supported because they get completely deleted or something. No point in removing people's choice to play offline with their mojang account. I'll close this like I did last time since there's still no point in removing it.

I'd welcome a new PR for adding warnings regarding the lack of online support in mojang accounts though.

**Pull request closed without merging**
