### PR TITLE
Switch logo font to Josefin Sans

### PR DESCRIPTION
**Pull request by Scrumplex**
Screenshot

---

See for yourself: https://github.com/Scrumplex/PolyMC/tree/update-logo

Uses `Josefin Sans` instead of `Heebo` and slightly different padding.

### CODE REVIEW

**Review by ZekeZDev — APPROVED** [review]

**Review by ZekeZDev — CHANGES_REQUESTED** [review]
I think we should actually look more into the font I am not really sold on this one and working with it on the website it has some weird issues.

**Review by ZekeZDev — APPROVED** [review]

**Comment by ZekeZDev** [comment]
Umm readme shouldnt be causing a rebuild

**Comment by Scrumplex** [comment]
> Umm readme shouldnt be causing a rebuild

but `program_info` does.

**Comment by txtsd** [comment]
Are the lineheights supposed to be unequal? The 'l' is tallest, 'P' is medium, and 'MC' is short.

**Comment by Scrumplex** [comment]
> Are the lineheights supposed to be unequal? The 'l' is tallest, 'P' is medium, and 'MC' is short.

I scaled `MC` down a little, as it was too pronounced before. `P` and `l` being different sizes comes down to the font itself. This is actually intended. The keyword here is *visual balance*. The `P` has more mass at the top, than the `l`, so to compensate the `l` is slightly larger

**Comment by txtsd** [comment]
Okay, that's fair.

**Review by txtsd — APPROVED** [review]

**Review by timoreo22 — APPROVED** [review]

**Review by d-513 — APPROVED** [review]

**Pull request merged**
