### PR TITLE
Add initial sorting function

### LINKED ISSUE #691: Sort icons in the icon selector by file name
### Role

The icons don't seem to be in any useful order

### Suggestion

Put the icons in order of filename

### Benefit

So its much easier to find the icon I want

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

I'm just looking for something similar to how a file browser would order the files instead of just picking any random order.
I also made the same bug report in multimc and a comment said they are sorted by date. It's probably the worse sorting order for that. All the instances are sorted by name and it makes they way easier to find.

### PR DESCRIPTION
**Pull request by mrmelon54**
Fixes #691 
Added a function `void IconList::sortIconList()` to sort all the icons by their `m_key` value using insertion sort (maybe a better sorting algorithm could be used?).
This is called at the end of `IconList::directoryChanged(const QString &path)` to update the order of icons to make them easier to find.

### CODE REVIEW

**Comment by flowln** [comment]
Can't you just use `std::sort` since you're using an iterator?

**Comment by mrmelon54** [comment]
> Can't you just use `std::sort` since you're using an iterator?

Honestly, I don't know much c++ so I had to figure out how to do that.

**Comment by flowln** [comment]
> Honestly, I don't know much c++ so I had to figure out how to do that.

don't worry :) you learn those things with time (i learned about `std::sort` from a uni assignment just last week for instance, nice coincidence being able to apply it here so soon :p)

**Comment by mrmelon54** [comment]
> > Honestly, I don't know much c++ so I had to figure out how to do that.
> 
> don't worry :) you learn those things with time (i learned about `std::sort` from a uni assignment just last week for instance, nice coincidence being able to apply it here so soon :p)

most other languages I have coded in have built-in sort functions so I have no idea why I didn't try looking it up first lol

**Comment by flowln** [comment]
I think it might be a good idea to do the `compare` case-insensitive. It being case-sensitive is quite unintuitive:
packs with uppercase name are shown before the others, disrespecting lexical order

**Comment by mrmelon54** [comment]
I don't have any icons that have capital letters so I didn't even notice lol

**Comment by mrmelon54** [comment]
I found `QString::localeAwareCompare()` and that seems to do the trick

**Review by flowln — APPROVED** [review]
seems to be working fine. thanks!

**Review by txtsd — APPROVED** [review]

**Review by Scrumplex — APPROVED** [review]
Thanks!

**Pull request merged**
