### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by technoalli3**
Readded the code of conduct, seems like you accidentally deleted it.

### CODE REVIEW

**Comment by AshtakaOOf** [comment]
Y E S

**Comment by dajix350** [comment]
Lmao

**Comment by ghost** [comment]
Lmao

**Comment by Weredime** [comment]
@LennyMcLennington What is your reasoning for this? There is no valid explanation from you about your recent questionable actions.

**Comment by justastranger** [comment]
> @LennyMcLennington What is your reasoning for this? There is no valid explanation from you about your recent questionable actions.

Bigotry and right-wing radicalization. Oh wait, they're the same picture. Somehow being a decent human being is RaDiCaL lEfTiSt QuEeR iDeOlOgY to bigots.

**Pull request closed without merging**
