### PR TITLE
Fix help translate link

### PR DESCRIPTION
**Pull request by JxxIT**
This fixes the help translate link

### CODE REVIEW

**Comment by DioEgizio** [comment]
no this doesn't, and this actually breaks translations in polymc

**Comment by JxxIT** [comment]
I think its fixed now

**Comment by DioEgizio** [comment]
This pr doesn't fix anything since it's already set to the right link

https://github.com/PolyMC/PolyMC/blob/e37f70b9f7e35639f49c2f53f8e82e97f5fbffc9/CMakeLists.txt#L105

**Comment by timoreo22** [comment]
Can confirm, translate link is correct, %1 is a format modifier, that gets filled in with the correct url

**Pull request closed without merging**
