### PR TITLE
Add NeoForge support

### PR DESCRIPTION
**Pull request by 62832**
Currently includes support for NeoForge-based modpacks from CurseForge and Modrinth. ATLauncher and Technic support has not been added yet since there are currently no NeoForge packs there to test with.

### CODE REVIEW

**Comment by Kaydax** [comment]
LBTM

**Comment by ghost** [comment]
Welcome to the Minecraft community where we have to support the delusions of a bunch of autists who ruin everything they touch.

**Comment by 62832** [comment]
You're an idiot. Casting aside any and all IdPol shit, NeoForge on a technical level is [a massive step forward](https://gist.github.com/TelepathicGrunt/4de77c67adb661c9380e594d20b6a58b) compared to Forge.

**Comment by BowDown097** [comment]
🏳️‍🌈

**Comment by ghost** [comment]
I'm not opposed to it if it works but I'm really not on board with supporting the next Quilt, formed out of delusions of prosecution by the mentally insane.

**Comment by TowerofCone** [comment]
Given the absolute state of Forge modding (_and the fact that, unlike Quilt, Neoforge has starting support and thus has begun to snowball already... don't get me started on how Lex's reputation helped with that, we'll be here all day_) and the fact that i really, REALLY don't want to jump to Prism nor return to MultiMC, i'd rather that support gets added before things get any worse.

**Comment by BowDown097** [comment]
> Given the absolute state of Forge modding (_and the fact that, unlike Quilt, Neoforge has starting support and thus has begun to snowball already... don't get me started on how Lex's reputation helped with that, we'll be here all day_) and the fact that i really, REALLY don't want to jump to Prism nor return to MultiMC, i'd rather that support gets added before things get any worse.

paid shill fr

**Comment by TowerofCone** [comment]
> paid shill fr

one with a generous wage of $0.00 if so.

**Comment by 62832** [comment]
I reiterate from a previous comment of mine that got marked as a violation of Acceptable Use Policies that NeoForge on a technical level is [a massive step forward](https://gist.github.com/TelepathicGrunt/4de77c67adb661c9380e594d20b6a58b) compared to Forge and has already gained large traction among modders from *both* Fabric and Forge.

**Comment by stvev1337** [comment]
Is there a way to manually install Neoforge in the meantime?

**Comment by 62832** [comment]
> Is there a way to manually install Neoforge in the meantime?

You should be able to build PolyMC from source with the included NeoForge support. I'm unsure if a build has been actually released yet with the new update.

**Pull request merged**
