### PR TITLE
Revert "Merge pull request #188 from PolyMC/removal/notifications"

### PR DESCRIPTION
**Pull request by d-513**
This reverts commit 5b8003c, reversing
changes made to c071910.

Readds notification system because it can be useful.
Needs PolyMC/files#1

### CODE REVIEW

**Comment by Scrumplex** [comment]
What's wrong with using news? We are going to create a news post about version 1.2.2 anyway. Imo this is just duplicate functionality.

**Comment by d-513** [comment]
> What's wrong with using news? We are going to create a news post about version 1.2.2 anyway. Imo this is just duplicate functionality.

Imo it's more visible, but idk

**Comment by d-513** [comment]
Also news don't have to have Werid attention grabbing names "IMPORTANT:"

**Comment by flowln** [comment]
I think the best thing would be to integrate some things of the notification system, like type of news or 'unread news', in the news system. Like dada said, the current system isn't really good at communicating notices to the users, so its impact is pretty minimal to the normal user imo

**Comment by d-513** [comment]
@txtsd wtf is happening with CI, you should add a timeout :/

**Comment by txtsd** [comment]
> @txtsd wtf is happening with CI, you should add a timeout :/

What was this about?

**Comment by d-513** [comment]
> > @txtsd wtf is happening with CI, you should add a timeout :/
> 
> What was this about?

Lmao the cache was running for 12hours

**Comment by txtsd** [comment]
Which build was it on? Windows uses a different action than the others. I'll file an issue upstream.

**Comment by d-513** [comment]
> Which build was it on? Windows uses a different action than the others. I'll file an issue upstream.

Windows. But rebuild fixed it. And it was only one of the builds. Looks like GHA died because it had retrieved 98% of cache and was stuck

**Comment by flowln** [comment]
hmm will this be done in the end? I think we should focus on improving the news system rather than having the two systems, it's less awkward like that imo

**Pull request closed without merging**
