### PR TITLE
License for assets

### PR DESCRIPTION
**Pull request by ZekeZDev**
The PolyMC logo and assets are licensed under the CC BY-NC-SA 4.0 having it in this folder should help to clear this up.

### CODE REVIEW

**Comment by d-513** [comment]
This might add confusion, there are desktop files and metadata in that folder aswell.
Metadata is licensed CC0

**Comment by ZekeZDev** [comment]
What do you think the best approach would be to license between them?

**Comment by ghost** [comment]
register each individual file in PolyMC as a trademark and sue everyone who has a single line of code that is identical to one in PolyMC

**Comment by d-513** [comment]
> What do you think the best approach would be to license between them?

Just say in the LICENSE file in program_info that that only applies to logos

**Comment by ZekeZDev** [comment]
@dada513 does that look good?

**Review by timoreo22 — APPROVED** [review]
All good !

**Pull request merged**
