### PR TITLE
Hopefully fix JavaChecker

### PR DESCRIPTION
**Pull request by cozyGalvinism**
I replaced the int for the status code with a bool, which is then just checked.

Also, the checker exits early now, if one of the properties isn't available, which isn't a necessary change but whatever.

The return code also only needs to be explicitly set, if it isn't 0.

### CODE REVIEW

**Comment by Scrumplex** [comment]
Semantically, this doesn't seem to make any difference? Apart from breaking early

**Comment by cozyGalvinism** [comment]
Well, for some reason the compiled version of the previous iteration resulted in `System.exit` being called with a boolean value, though this could also just come from the decompiler I'm using (jd-gui). The other reason why it might fail is if the properties just aren't present. A friend of mine has the issue too and they just have the Oracle Java installed.

**Comment by Scrumplex** [comment]
Okay. Might as well optimize even more and call `System.exit(1)` instead of setting `error = true`

**Comment by txtsd** [comment]
> Okay. Might as well optimize even more and call `System.exit(1)` instead of setting `error = true`

Yea, just exit instead of break.

**Comment by txtsd** [comment]
It would be nice to print the error to log too!

**Comment by TheGlitch76** [comment]
> being called with a boolean value, though this could also just come from the decompiler I'm using

That's almost definitely your decompiler; poor quality decompilers sometimes incorrectly assume integers are booleans in bytecode

**Comment by Scrumplex** [comment]
I think we can close this. Looks like it didn't fix #276

**Pull request closed without merging**
