### PR TITLE
Add more Nix `meta` information

### PR DESCRIPTION
**Pull request by TheOPtimal**
Adds changelog and download link into the Nix meta-info.

### CODE REVIEW

**Comment by flowln** [comment]
Please add a [DCO sign-off](https://github.com/PolyMC/PolyMC/blob/develop/CONTRIBUTING.md#signing-your-work) as the bot says.

**Comment by TheOPtimal** [comment]
> Please add a [DCO sign-off](https://github.com/PolyMC/PolyMC/blob/develop/CONTRIBUTING.md?rgh-link-date=2022-07-18T18%3A14%3A30Z#signing-your-work) as the bot says.

How can I do that after the commit has already been made and has been pushed?

**Comment by flowln** [comment]
> How can I do that after the commit has already been made and has been pushed?

Either do a remediation commit or force-push with your signature amended. See https://github.com/PolyMC/PolyMC/pull/930/checks?check_run_id=7395031191, it explains both options

**Comment by TheOPtimal** [comment]
Done.

**Review by flowln — APPROVED** [review]
thanks

**Review by Scrumplex — APPROVED** [review]
Thanks

**Review by txtsd — APPROVED** [review]

**Pull request merged**
