### PR TITLE
Further development of PolyMC's *unique* brand identity.

### PR DESCRIPTION
**Pull request by Regular-Baf**
I apologise in advance for this.

### CODE REVIEW

**Review by ZekeZDev — APPROVED** [review]

**Review by DioEgizio — CHANGES_REQUESTED** [review]
Cursed

**Comment by glowiak** [comment]
And that's good

**Comment by timoreo22** [comment]
What the fuck is this

**Comment by Scrumplex** [comment]
I have never seen something as cursed as this

**Comment by timoreo22** [comment]
I almost want to approve this

**Comment by DioEgizio** [comment]
this is too cursed, but we could recycle it for an April fools joke

**Comment by txtsd** [comment]
Rename it to `catbgrnd3.png` and add code to show it only on April 1st.

**Comment by Regular-Baf** [comment]
> Rename it to `catbgrnd3.png` and add code to show it only on April 1st.

I'm not smart enough for this but I'll look into it.

**Review by kthchew — APPROVED** [review]
average cat fan vs average polykitty enjoyer

**Review by d-513 — APPROVED** [review]
truetrue

**Review by timoreo22 — APPROVED** [review]
fuck it

**Comment by flowln** [comment]
:eyes:

**Comment by Un1q32** [comment]
if we use this for an april fools joke then it should also play a vine boom sound effect when polykitty is shown

**Comment by d-513** [comment]
approve it for da vine

**Comment by d-513** [comment]
Wait I can actually merge this

**Review by txtsd — DISMISSED** [review]
MERGE BLOCK!

**Review by Scrumplex — DISMISSED** [review]
MERGE BLOCK 2!!!

**Review by DioEgizio — CHANGES_REQUESTED** [review]
no u

**Comment by d-513** [comment]
Literally 1984

**Comment by Regular-Baf** [comment]
Please merge it would make me so happy :>

**Comment by Scrumplex** [comment]
Closed. Reason: too heated

**Comment by d-513** [comment]
Literally 1984

**Pull request closed without merging**
