### PR TITLE
Fix release workflow

### PR DESCRIPTION
**Pull request by Scrumplex**
This should fix our release workflow.

### CODE REVIEW

**Review by txtsd — APPROVED** [review]

**Review by ZekeZDev — APPROVED** [review]

**Comment by Scrumplex** [comment]
I haven't tested this yet lol. Let me test it in my fork

**Comment by Scrumplex** [comment]
This works.

**Review by d-513 — APPROVED** [review]
what was broken btw?

**Comment by Scrumplex** [comment]
> what was broken btw?

Some tarballs/zips weren't added to the GH release

**Pull request merged**
