### PR TITLE
Never invalidate libraries cache entries by time elapsed

### LINKED ISSUE #1071: Newest Action-Build reloads Minecraft-Library every time
### Operating System

Linux

### Version of PolyMC

PolyMc 1.4.0-da70a3a4 AppImage Version

### Version of Qt

Qt 6.2.4

### Description of bug

Every Time when i start one of my instances, Polymc reloads the Librarys and it semms that the Launcher has some saving problems

### Steps to reproduce

Just open PolyMC and try to launch an instance.

### Suspected cause

_No response_

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### PR DESCRIPTION
**Pull request by flowln**
Fixes #1071

This allows you to mark a cached result as eternal, meaning it'll never expire as a result of being too old. It is applied to libraries and FML libs to restore the behavior prior to #920. It will, however, invalidate the cache one last time, because old entries will not have the eternal bool in the `metacache`. Is this fine? :thinking:

### CODE REVIEW

**Comment by Scrumplex** [comment]
This is probably okay. Though I do not know, if Mojang might not update libraries without changing their version number

**Comment by flowln** [comment]
> This is probably okay. Though I do not know, if Mojang might not update libraries without changing their version number

I'd guess it's probably fine anyway. If they don't update their version number, their SHA1 hash will change anyway, which ought to make it work as intended. Anyway, it should work the same as before those cache changes i made, so if there's an issue with that old code, this is not the PR to mess with it.

**Review by Scrumplex — APPROVED** [review]
LGTM

**Review by timoreo22 — APPROVED** [review]
oops, forgot to review this one

**Pull request merged**
