### PR TITLE
Limit instance names to 128 chars

### LINKED ISSUE #197: limit the length of instance names
### Role

create instances

### Suggestion

limit the length of instance names and/or limit the length displayed

### Benefit

to prevent the gui from changing layout when an instance with a long name is selected and prevent unclear errors from showing

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

image
currently instances with long names mess with the layout
image
the error when a name is above 255 characters (the limit for a file name in linux) is very unclear so a limit would prevent this from showing

### PR DESCRIPTION
**Pull request by Scrumplex**
Closes #197

This makes it a little better than keeping it unlimited.

### CODE REVIEW

**Comment by ZekeZDev** [comment]
Whats the reason for being 128? Isnt the actual limit 255?

**Comment by luni3359** [comment]
Probably something to do with the length of the path? Since it seems the folders are created with the exact same name you input for your instances.

**Comment by txtsd** [comment]
In that case we should truncate the filenames and add a hash

**Comment by Scrumplex** [comment]
128 was arbitrary. The UI doesn't handle long instance nes very well anyway so it should be fine

**Review by txtsd — APPROVED** [review]

**Review by d-513 — APPROVED** [review]

**Review by ZekeZDev — APPROVED** [review]

**Pull request merged**
