### PR TITLE
Update org.polymc.PolyMC.metainfo.xml.in

### PR DESCRIPTION
**Pull request by byquanton**
Should fix Flatpak/Flathub build

### CODE REVIEW

**Comment by d-513** [comment]
thanks, I was busy

**Comment by d-513** [comment]
It's still complaining about
```
• style-invalid         : <image> has vertical padding [https://polymc.org/img/screenshots/LauncherDark.png]
• style-invalid         : <image> has horizontal padding [https://polymc.org/img/screenshots/LauncherDark.png]
• style-invalid         : <image> has vertical padding [https://polymc.org/img/screenshots/LauncherCatDark.png]
• style-invalid         : <image> has horizontal padding [https://polymc.org/img/screenshots/LauncherCatDark.png]
• style-invalid         : <caption> is too short [Cat :)];shortest allowed is 10 chars
• style-invalid         : <image> has vertical padding [https://polymc.org/img/screenshots/PropertiesDark.png]
• style-invalid         : <image> has horizontal padding [https://polymc.org/img/screenshots/PropertiesDark.png]
• style-invalid         : <image> has vertical padding [https://polymc.org/img/screenshots/ModInstallDark.png]
• style-invalid         : <image> has horizontal padding [https://polymc.org/img/screenshots/ModInstallDark.png]
• style-invalid         : <image> has vertical padding [https://polymc.org/img/screenshots/ModpackInstallDark.png]
• style-invalid         : <image> has horizontal padding [https://polymc.org/img/screenshots/ModpackInstallDark.png]
```
but maybe flathub will let it slide

**Comment by d-513** [comment]
added patch in flatpak, https://github.com/flathub/org.polymc.PolyMC/commit/46c7fd99bcbc748e12ce454f2150c33affb910d2, lets see

**Comment by byquanton** [comment]
SUCCESS :) 
https://flathub.org/builds/#/builders/39/builds/11197

**Comment by flowln** [comment]
Is there a way of just not using the width / height of the image? Like, getting it directly from the images? That would prevent breaks like this one in the future.

Or, maybe we could have the images saved in another place, so that changes to the website don't break the Flatpak, and then we could update both the images and this metadata at once.

**Comment by d-513** [comment]
> Is there a way of just not using the width / height of the image? Like, getting it directly from the images? That would prevent breaks like this one in the future.
> 
> Or, maybe we could have the images saved in another place, so that changes to the website don't break the Flatpak, and then we could update both the images and this metadata at once.

its required i think, flatpak moment

**Review by d-513 — APPROVED** [review]

**Review by flowln — APPROVED** [review]
thank you!

**Review by Scrumplex — APPROVED** [review]
Thanks

**Pull request merged**
