### PR TITLE
Enable LTO/IPO on release builds

### LINKED ISSUE #268: cannot compile with link time optimization
### Operating System

Linux

### Description of bug

compiling PolyMC with `-flto=auto` causes undefined references to libnbtplusplus

### Steps to reproduce

compile with `-flto=auto`
e.g.
```
env CXXFLAGS="-flto=auto" cmake -B builddir
cmake --build builddir
```

### Suspected cause

the a archive for libnbtplusplus gets stripped as part of link time optimization

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### PR DESCRIPTION
**Pull request by oynqr**
This enables LTO on Release/MinSizeRel builds. All binaries will have to be tested.

Closes #268 
~~Requires https://github.com/PolyMC/libnbtplusplus/pull/2~~
Requires https://github.com/PolyMC/libnbtplusplus/pull/3

### CODE REVIEW

**Comment by Scrumplex** [comment]
Shouldn't this be the choice of the packager?

On Arch for example LTO is off by default, but can be enabled either per-package or globally using makepkg's `lto` option

**Comment by oynqr** [comment]
> Shouldn't this be the choice of the packager?

I agree.

Now, this should give an easy way of specifying -DENABLE_LTO=ON for packaging systems that don't support setting the correct LTO flags themselves and leave those alone that do.
Also, what do you think about enabling it on Actions builds?

**Comment by Scrumplex** [comment]
I would like having it in our builds. Not sure how well it works on macOS and Windows, but I guess we can just try it out :D

**Comment by Scrumplex** [comment]
Cool. Seems like LTO/IPO works on all platforms.

**Review by Scrumplex — APPROVED** [review]

**Comment by Jan200101** [comment]
a little testing has shown that when compiling with `-DNBT_BUILD_SHARED:BOOL=ON` libnbtplusplus spits out the following errors
```
/tmp/tmp.9XiPwKhGUo/PolyMC/libraries/libnbtplusplus/src/tag_array.cpp:130:27: error: type attributes ignored after type is already defined [-Werror=attributes]
  130 | template class NBT_EXPORT tag_array<int8_t>;
      |                           ^~~~~~~~~~~~~~~~~
/tmp/tmp.9XiPwKhGUo/PolyMC/libraries/libnbtplusplus/src/tag_array.cpp:132:27: error: type attributes ignored after type is already defined [-Werror=attributes]
  132 | template class NBT_EXPORT tag_array<int64_t>;
      |                           ^~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
```

This is on a fresh clone from this PR with no extra flags.

The warning is upgraded to an error because of the CXX flags PolyMC sets by default
https://github.com/PolyMC/PolyMC/blob/c7fdfb811669a863606dc0a26186c0ab827db9c6/CMakeLists.txt#L37

**Comment by Scrumplex** [comment]
> The warning is upgraded to an error because of the CXX flags PolyMC sets by default

Those suck. I changed them in #127 but we are still holding on to older Qt versions for the time being

**Comment by oynqr** [comment]
Does anyone know a better way than just moving the templated methods to the header file and setting them inline, which this does?

**Review by ZekeZDev — APPROVED** [review]

**Comment by txtsd** [comment]
This is gonna conflict with #336

**Comment by Scrumplex** [comment]
> Does anyone know a better way than just moving the templated methods to the header file and setting them inline, which this does?

I guess this is fine for now

**Comment by oynqr** [comment]
> This is gonna conflict with #336

I'll rebase if #336 gets merged first.

**Review by txtsd — APPROVED** [review]

**Pull request merged**
