### PR TITLE
Change margins in Custom Commands settings for consistency

### LINKED ISSUE #555: Margins in custom commands settings is inconsistent with other settings pages
### Operating System

macOS

### Description of bug

(minor UI bug)

The margin length around the options in the "Custom Commands" settings does not match the margins around the options in the other settings pages. This is inconsistent, and the margins in the custom commands page on the left and right should be increased, and the margins on the top should be decreased to match.

https://user-images.githubusercontent.com/79120643/167962410-4201d50d-1d69-439d-8e9e-36d5aefe7472.mov

### Steps to reproduce

1. Open PolyMC settings
2. Open the Custom Commands tab

### Suspected cause

_No response_

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### PR DESCRIPTION
**Pull request by kthchew**
Fixes #555

### CODE REVIEW

**Comment by LennyMcLennington** [comment]
This breaks the margins on other platforms

**Comment by kthchew** [comment]
Thanks for checking, I made the change macOS-only.

**Comment by LennyMcLennington** [comment]
@kthchew I took a guess at what I think might be the underlying issue, does the commit I made fix the problem? If it does work, it would probably be better to fix it this way than to manually change some layout properties based on the operating system.

**Comment by kthchew** [comment]
> @kthchew I took a guess at what I think might be the underlying issue, does the commit I made fix the problem? If it does work, it would probably be better to fix it this way than to manually change some layout properties based on the operating system.

Thanks! It's mostly good, but the margin length on the top is still a bit too much. For reference (Java is correct, Custom Commands is incorrect):

Screen Shot 2022-05-12 at 10 10 21 PM
Screen Shot 2022-05-12 at 10 10 29 PM

**Comment by LennyMcLennington** [comment]
This change was just a complete guess, is the margin still broken?

**Comment by Scrumplex** [comment]
Maybe it is time to get rid of the CustomCommands widget. I don't even know why it's the only thing that's a widget while everything else isn't.

**Comment by LennyMcLennington** [comment]
> Maybe it is time to get rid of the CustomCommands widget. I don't even know why it's the only thing that's a widget while everything else isn't.

So it can be reused in multiple places I guess. Not sure why the others aren't widgets since they're also used in multiple places. Reduces duplicated code.

**Comment by Scrumplex** [comment]
> > Maybe it is time to get rid of the CustomCommands widget. I don't even know why it's the only thing that's a widget while everything else isn't.
> 
> So it can be reused in multiple places I guess. Not sure why the others aren't widgets since they're also used in multiple places. Reduces duplicated code.

But we don't do that with any other settings page.

**Comment by LennyMcLennington** [comment]
> > > Maybe it is time to get rid of the CustomCommands widget. I don't even know why it's the only thing that's a widget while everything else isn't.
> > 
> > 
> > So it can be reused in multiple places I guess. Not sure why the others aren't widgets since they're also used in multiple places. Reduces duplicated code.
> 
> But we don't do that with any other settings page.

Yeah I know but it might be good to do it to reduce duplication.

**Comment by kthchew** [comment]
> This change was just a complete guess, is the margin still broken?

Now the top margin is fine, but the left/right margins are worse than before :c

Screen Shot 2022-05-13 at 3 23 55 PM

**Comment by LennyMcLennington** [comment]
This is too confusing for me especially since i dont have a mac i can't see the layout without having to ask someone else to run the code on a mac, if anyone else with a mac wants to try and find the problem that would be great but if not we can just revert this back to the original hacky fix and use it as a temporary fix until we can figure out a proper one

**Comment by kthchew** [comment]
Fair enough. I'm confused too, and I don't even need to ask someone else to test it for me.

I'll see if I can give it a go through the `.ui` file in a few days.

**Comment by kthchew** [comment]
OK, it gets weirder. On your original commit (0a561a2daca6e135f50f89f43a25b2625330b6e6), if I set the color to "dark" instead of "system," then the margins are correct. When set to "system" (default), then they are broken as I described above.

The latest commit has margins that are too small on both color schemes.

And as for my original fix, that breaks the margins when the color scheme is "dark."

Without any fixes (latest release version), the margins are still a little off with both the dark and system themes.

It seems like the Qt system theme is trying to adapt to the platform or something, which causes this (I'm not exactly sure what it's doing). I suppose the only fix for this is to drop the CustomCommands widget, or make everything else a widget as well, unless I'm missing something (which is pretty likely).

**Comment by LennyMcLennington** [comment]
> OK, it gets weirder. On your original commit ([0a561a2](https://github.com/PolyMC/PolyMC/commit/0a561a2daca6e135f50f89f43a25b2625330b6e6)), if I set the color to "dark" instead of "system," then the margins are correct. When set to "system" (default), then they are broken as I described above.
> 
> The latest commit has margins that are too small on both color schemes.
> 
> And as for my original fix, that breaks the margins when the color scheme is "dark."
> 
> Without any fixes (latest release version), the margins are still a little off with both the dark and system themes.
> 
> It seems like the Qt system theme is trying to adapt to the platform or something, which causes this (I'm not exactly sure what it's doing). I suppose the only fix for this is to drop the CustomCommands widget, or make everything else a widget as well, unless I'm missing something (which is pretty likely).

Yeah I have no idea what I'm missing I went through the ui files and can't tell the difference so maybe it will be better to just drop the widget and see if that works.

**Comment by kthchew** [comment]
I will close this for now and come back to it once I have the time to experiment with this.

**Pull request closed without merging**
