### PR TITLE
Consider a new macOS only icon PR

### PR DESCRIPTION
**Pull request by Zenith222**
#821

### CODE REVIEW

**Comment by LennyMcLennington** [comment]
Not opposed to changing the icon but I don't like the one proposed in this PR

**Comment by Zenith222** [comment]
> Not opposed to changing the icon but I don't like the one proposed in this PR

"I don't like" is very vague. Would you mind being more specific? Open to suggestions.

**Review by kthchew — COMMENTED** [review]
In general I like this design better. I have a few comments though:

- Any reason the drop shadow was removed? It's quite typical for macOS app icons to have it.
- The brown sections of the new icon have less contrasting shades of brown than the old icon. Does the icon look better this way or with the old colors? (I'm not very good with visualizing this, so if it's not too much trouble maybe you could try this new design with the old colors?) I feel like the colors shouldn't be changed too much across platforms if it can be helped.

**Comment by Zenith222** [comment]
> In general I like this design better. I have a few comments though:
> 
> * Any reason the drop shadow was removed? It's quite typical for macOS app icons to have it.
> * The brown sections of the new icon have less contrasting shades of brown than the old icon. Does the icon look better this way or with the old colors? (I'm not very good with visualizing this, so if it's not too much trouble maybe you could try this new design with the old colors?) I feel like the colors shouldn't be changed too much across platforms if it can be helped.

I took your feedback and added a more obvious drop shadow as well as adjusted the contrast of the top of the icon. I also made a version with better matching darker brown colors. I like the lower contrast look, which unfortunately does mean changing the color a bit. This remixed logo doesn't feel as 3D as the real logo, because of the shape, so I play into the geometric aspects of the design rather than using dark shadows as the original design does. 

Please check out proposition 2 in the original post.

**Comment by ZekeZDev** [comment]
Im going to be honest, I don't like this design I feel like it looks a lot more dated and I would rather if the pentagon shape is kept. There has been some WIP macos logos I have been working on and I am happy to work with you on one but as of current I dont think this concept is suitable.

I am going to close this pr and allow for further discussion of this in #821.

WIP concept logos:
org polymc PolyMC bigsur-2
unknown-13

**Comment by Zenith222** [comment]
> Im going to be honest, I don't like this design I feel like it looks a lot more dated and I would rather if the pentagon shape is kept. There has been some WIP macos logos I have been working on and I am happy to work with you on one but as of current I dont think this concept is suitable.
> 
> I am going to close this pr and allow for further discussion of this in #821.
> 
> WIP concept logos: org polymc PolyMC bigsur-2 unknown-13

I'm inclined to agree with you on this. If you're more willing to adapt a different PolyMC logo at the time of the ManyMC and PolyMC merge (which I assume will happen) then there is no place for this adaptation of a dated logo at this time. 👍

**Comment by luni3359** [comment]
That first logo looks sick, I love it

**Comment by DioEgizio** [comment]
> Im going to be honest, I don't like this design I feel like it looks a lot more dated and I would rather if the pentagon shape is kept. There has been some WIP macos logos I have been working on and I am happy to work with you on one but as of current I dont think this concept is suitable.
> 
> I am going to close this pr and allow for further discussion of this in #821.
> 
> WIP concept logos: org polymc PolyMC bigsur-2 unknown-13

I prefer the current logo tbh

**Comment by jobukkit** [comment]
> > Im going to be honest, I don't like this design I feel like it looks a lot more dated and I would rather if the pentagon shape is kept. There has been some WIP macos logos I have been working on and I am happy to work with you on one but as of current I dont think this concept is suitable.
> > I am going to close this pr and allow for further discussion of this in #821.
> > WIP concept logos: org polymc PolyMC bigsur-2 unknown-13
> 
> I'm inclined to agree with you on this. If you're more willing to adapt a different PolyMC logo at the time of the ManyMC and PolyMC merge (which I assume will happen) then there is no place for this adaptation of a dated logo at this time. 👍

I like the white one!

**Pull request closed without merging**
