### PR TITLE
add sdkman scanning

### PR DESCRIPTION
**Pull request by Sneedplex**

### CODE REVIEW

**Comment by HeyaGlitz** [comment]
why

**Comment by LennyMcLennington** [comment]
Why not?

**Comment by HeyaGlitz** [comment]
Pretty sure line 461 and 462 have the same effect as this

**Comment by crueter** [comment]
That's old code that doesn't work lmao I forgot to remove it

**Comment by Sneedplex** [comment]
MacOS took 6 hours to create a Sparkle signature lmao maccers don't deserve rights

**Pull request closed without merging**
