### PR TITLE
fix(modrinth): fix sorting

### LINKED ISSUE #833: modrinth modpack sort is completely broken
### Operating System

Windows, macOS, Linux, Other

### Version of PolyMC

every polymc release with modrinth pack downloader

### Description of bug

go to the modrinth pack downloader
change sort
see mess

eg
polymc

but on knossos

knossos

### Steps to reproduce

- go to the modrinth pack downloader
- change sort
- see mess

### Suspected cause

🤷 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### PR DESCRIPTION
**Pull request by DioEgizio**
closes #833

### CODE REVIEW

**Comment by flowln** [comment]
Heh, looks like I was too slow to avoid duplicate work :p

The only problem I see with this is that, the only reason this issue exists at all, is that the translatable text and the one used in the API request, are defined in separate parts, and their index is _assumed_ to be the same. To avoid this kind of problem in the future, I was thinking it would be better to use that same function, for both translatable and API text, selecting between them with a `bool`. Then, in the API page, instead of adding each text to the UI separately, we would just do a `for`, getting the text at the index via this function and adding it to the UI.

**Review by Scrumplex — APPROVED** [review]

**Comment by Scrumplex** [comment]
Maybe we should just put all sorting options into a QMap.

**Review by ZekeZDev — APPROVED** [review]

**Review by timoreo22 — APPROVED** [review]
Arrays start at 0

**Comment by DioEgizio** [comment]
3 reviews 👀

**Pull request merged**
