### PR TITLE
Remove reference to legacy Minecraft accounts

### PR DESCRIPTION
**Pull request by ghost**
Maybe even remove the mojang part?

### CODE REVIEW

**Comment by DioEgizio** [comment]
> Maybe even remove the mojang part?

mojang accounts still work

**Comment by ghost** [comment]
Yeah, but "minecraft" accounts is not a thing anymore.

**Review by d-513 — APPROVED** [review]

**Review by Scrumplex — APPROVED** [review]

**Comment by Scrumplex** [comment]
The Mojang part will be removed once Mojang accounts stop working completely (we merged a workaround in #482). Once Mojang accounts stop working we will merge #354

**Comment by LennyMcLennington** [comment]
To be correct you could have it as "you must add at least one Minecraft, Mojang, or Microsoft account" but why not just change the wording to "you must have added at least one account that owns minecraft" instead of mentioning all the specific types of accounts? Also I haven't heard of Minecraft accounts no longer being a thing, Microsoft hasn't stopped supporting yggdrasil.

**Review by flowln — APPROVED** [review]

**Pull request merged**
