### PR TITLE
Refactor resource models

### PR DESCRIPTION
**Pull request by flowln**
Hello! :)

This builds up the work started in #652 of decoupling resource types to allow for better flexibility in implement resource-specific features. In particular, this is a preliminary work towards better support for resources other than mods, such as Resource Packs and Shader Packs.

The idea here is to separate Mods from other types of resources, so that we can work on those separately without incurring changes on the other resource types. It's similar to how #652 allows for resource type specific buttons on that resource's page.

My idea here was to create a hierarchy in which `Resource` is the base class for all resources, implementing common features to all of them, and have the types of resources subclass it to add their own behavior. Similarly, `ResourceFolderModel` becomes the basic implementation for all resource types, being able to be subclassed to provide custom acessors and information display specific to that resource type (e.g. Resource packs aren't yet parsed, so we can't know it's pack version, and so the 'Version' column remained empty most of the time, so there was no need to show it).

Since it's all refactorings, there should be no behavior difference from this PR. The only differences are the removal of the 'Version' column in non-mods lists, and the translation strings (should i make translations for the non-mods lists specifically?).

I don't know if what i've done is the best solution (i particularly think the `static_cast`s and templates are a bit meh, but how to avoid it?), so i'd like some feedback (as always)!

Known issue:
Sometimes the tests fail due to a failed assert in Qt code or thread thingy (i can reproduce it somewhat consistently when running the tests 1000 times ~don't ask me why i ran the test 1000 times~, if anyone wants to run it do `ctest --output-on-failure --repeat-until-fail 1000 -R "ResourceFolderModel"`). I've tried my best to find out why this happens, but wasn't able to :c If anyone finds out why, please tell me!

### CODE REVIEW

**Comment by Scrumplex** [comment]
conflicting with develop

**Review by Scrumplex — APPROVED** [review]
Good idea and implementation :+1:

**Review by timoreo22 — APPROVED** [review]
I'm gonna regret it

**Comment by BeansBeefBroccoli** [comment]
Two Approvals

**Comment by DioEgizio** [comment]
2 approvals 👀

**Comment by flowln** [comment]
if anyone finds out why the known issue exists, please tell me!
*i really hope this PR being merged doesn't break everything*

**Comment by Scrumplex** [comment]
> i really hope this PR being merged doesn't break everything

:trollface:

**Pull request merged**
