### PR TITLE
specify -DLauncher_BUILD_PLATFORM on CI builds (EDIT: also remove "on x")

### PR DESCRIPTION
**Pull request by DioEgizio**
more cool
also maybe helps with updater?

now on the title it shows the platform

immagine

### CODE REVIEW

**Comment by Scrumplex** [comment]
Hmm. I personally don't like that it's included in the full version string. Maybe we can just remove it from there

**Comment by DioEgizio** [comment]
wdym

**Comment by Scrumplex** [comment]
Look at your window title there, it says "on Linux".

**Comment by DioEgizio** [comment]
yeah that's the point of the pr.

**Comment by DioEgizio** [comment]
So this isn't wanted?

**Comment by d-513** [comment]
This is good I actually started to set this on flatpak and Debian.

**Review by d-513 — APPROVED** [review]

**Comment by DioEgizio** [comment]
Yeah it's cool and also other packages like Void do it

**Comment by luni3359** [comment]
I don't think this is a good change because it makes the titlebar look very crowded. Is there any program that includes that info in its titlebar? It would fit better under "About PolyMC".

**Comment by DioEgizio** [comment]
> I don't think this is a good change because it makes the titlebar look very crowded. Is there any program that includes that info in its titlebar? It would fit better under "About PolyMC".

It already applies to About PolyMC. Except the fact that it'll be necessary with updating, I don't think it's a so annoying thing to have in the titlebar and i think it's cool

**Comment by DioEgizio** [comment]
When you misclick

**Comment by luni3359** [comment]
I understand that it'll help with updating but I don't think it looks cool on the titlebar. No program actually does this.

**Comment by DioEgizio** [comment]
MultiMC does, this is a relic from MultiMC.

**Comment by kthchew** [comment]
I agree with @Scrumplex and @luni3359. Users (usually…) already know what OS they’re using; I’d be pretty annoyed if every program on my system put “(app name) on (OS)” in their title.

I think it’s a good change to make internally (e.g. to pave the way for a future updater), but I don’t think it should be shown to a user (maybe it makes sense in the about dialog). I didn’t really like this from MultiMC.

**Comment by DioEgizio** [comment]
I likes this but I seem to be in a minority

**Comment by luni3359** [comment]
No it's just a matter of fixing #335 first and then this PR can be merged.

**Comment by d-513** [comment]
bruh egizo this is fine the titlebar issue is absolutely another thing, it shouldnt say PolyMC on <os> but the option should be used

**Comment by d-513** [comment]
Patch:
```
From 1bb35b9204b6a6830610acd99090a4f58706dcab Mon Sep 17 00:00:00 2001
From: DioEgizio <83089242+DioEgizio@users.noreply.github.com>
Date: Mon, 18 Apr 2022 12:09:24 +0200
Subject: [PATCH] specify -DLauncher_BUILD_PLATFORM on CI builds

more cool
also maybe helps with updater?
---
 .github/workflows/build.yml | 6 +++---
 1 file changed, 3 insertions(+), 3 deletions(-)

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
index 196b6d79..c22baed3 100644
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -104,18 +104,18 @@ jobs:
       - name: Configure CMake (macOS)
         if: runner.os == 'macOS'
         run: |
-          cmake -S . -B ${{ env.BUILD_DIR }} -DCMAKE_INSTALL_PREFIX=${{ env.INSTALL_DIR }} -DCMAKE_BUILD_TYPE=${{ inputs.build_type }} -DENABLE_LTO=ON -DQt5_DIR=/usr/local/opt/qt@5 -DCMAKE_PREFIX_PATH=/usr/local/opt/qt@5 -G Ninja
+          cmake -S . -B ${{ env.BUILD_DIR }} -DCMAKE_INSTALL_PREFIX=${{ env.INSTALL_DIR }} -DCMAKE_BUILD_TYPE=${{ inputs.build_type }} -DENABLE_LTO=ON -DQt5_DIR=/usr/local/opt/qt@5 -DCMAKE_PREFIX_PATH=/usr/local/opt/qt@5 -DLauncher_BUILD_PLATFORM=macOS -G Ninja
 
       - name: Configure CMake (Windows)
         if: runner.os == 'Windows'
         shell: msys2 {0}
         run: |
-          cmake -S . -B ${{ env.BUILD_DIR }} -DCMAKE_INSTALL_PREFIX=${{ env.INSTALL_DIR }} -DCMAKE_BUILD_TYPE=${{ inputs.build_type }} -DENABLE_LTO=ON -G Ninja
+          cmake -S . -B ${{ env.BUILD_DIR }} -DCMAKE_INSTALL_PREFIX=${{ env.INSTALL_DIR }} -DCMAKE_BUILD_TYPE=${{ inputs.build_type }} -DENABLE_LTO=ON -DLauncher_BUILD_PLATFORM=${{ matrix.name }} -G Ninja
 
       - name: Configure CMake (Linux)
         if: runner.os == 'Linux'
         run: |
-          cmake -S . -B ${{ env.BUILD_DIR }} -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=${{ inputs.build_type }} -DENABLE_LTO=ON -G Ninja 
+          cmake -S . -B ${{ env.BUILD_DIR }} -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=${{ inputs.build_type }} -DENABLE_LTO=ON -DLauncher_BUILD_PLATFORM=Linux -G Ninja 
 
       ##
       # BUILD

```

**Comment by DioEgizio** [comment]
> I agree with @Scrumplex and @luni3359. Users (usually…) already know what OS they’re using; I’d be pretty annoyed if every program on my system put “(app name) on (OS)” in their title.
> 
> I think it’s a good change to make internally (e.g. to pave the way for a future updater), but I don’t think it should be shown to a user (maybe it makes sense in the about dialog). I didn’t really like this from MultiMC.

Done!

**Comment by DioEgizio** [comment]
immagine

now it looks like this

**Review by txtsd — APPROVED** [review]

**Review by d-513 — APPROVED** [review]
dioegizo moment

**Comment by DioEgizio** [comment]
yes :pofat:

**Review by Scrumplex — APPROVED** [review]

**Pull request merged**
