### PR TITLE
[MACOS] Move app data to Application Support

### PR DESCRIPTION
**Pull request by d-513**
This is a fix that has been ported from [ManyMC](https://github.com/MinecraftMachina/ManyMC), this fixes MacOS data location so app updates dont delete instances and use the proper Application Support folder

GHA shows it builds fine. I would like someone with a Mac to test this first, as I don't have one

### CODE REVIEW

**Comment by DioEgizio** [comment]
I agree

**Comment by DioEgizio** [comment]
I will try this build when I go home

**Comment by DioEgizio** [comment]
Works fine

**Review by Scrumplex — APPROVED** [review]

**Comment by kloenk** [comment]
Cherry picked onto https://github.com/dada513/Polymc/tree/m1_support, builds and minecraft is able to start (with the local UA patch to get the log4j files).

**Comment by txtsd** [comment]
@Kloenk Can you whether the data is now stored in the `Application Support` folder itself, or inside a `PolyMC` folder under `Application Support`?

**Comment by kloenk** [comment]
It's inside `PolyMC` IIRC we should not have access to the upper folder. So it works as intended  and the files are under `$HOME/Library/Application\ Support/PolyMC`

**Comment by DioEgizio** [comment]
> It's inside `PolyMC` IIRC we should not have access to the upper folder. So it works as intended and the files are under `$HOME/Library/Application\ Support/PolyMC`

Yes I can confirm

**Comment by txtsd** [comment]
Okay thank you!

**Review by txtsd — APPROVED** [review]
LGTM!

**Review by timoreo22 — APPROVED** [review]
All good !

**Pull request merged**
