### PR TITLE
Improve cli usage

### LINKED ISSUE #285: cli: "Close PolyMC after game window opens" launches polymc when mc is closed
### Operating System

_No response_

### Description of bug

expected: polymc does not open after closing mc if lauched from the command line
what happens: polymc launches

### Steps to reproduce

enable the "Close PolyMC after game window opens" and launch a minecraft instance e.g.
polymc --launch 1.18.2
close minecraft
polymc is opened

### Suspected cause

_No response_

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### PR DESCRIPTION
**Pull request by flowln**
Adds two new checkboxes on the global settings, for controlling the behaviour of PolyMC when Minecraft closes, for the case where the option to close PolyMC when launching an instance is set.

Also adds a CLI option (-H or --hidedialogs) for hiding progress dialogs when initiating an instance, so that launching a specific instance is transparent when doing so from a third-party game library (e.g. Steam or Lutris)

Please test this, especially the "Reopen after crash" option! I wasn't able to test this property, though it _should_ work in theory...

### CODE REVIEW

**Comment by tonyaellie** [comment]
so the close PolyMC and open with crash will open polymc and the console window, whereas with just the close PolyMC only the console window will open on crash

**Comment by flowln** [comment]
> so the close PolyMC and open with crash will open polymc and the console window, whereas with just the close PolyMC only the console window will open on crash

Now the console shouldn't show up if the option isn't set!

**Comment by tonyaellie** [comment]
the console window still seems to be opening

**Comment by flowln** [comment]
**Now** it should be fixed!

**Comment by tonyaellie** [comment]
seems to work perfectly now

**Review by d-513 — APPROVED** [review]

**Review by Scrumplex — APPROVED** [review]

**Comment by Scrumplex** [comment]
This might bite #341

**Comment by flowln** [comment]
> This might bite #341

no human language can describe the disappointment im feeling right now T_T

Indeed, it seems like I need to change this PR a bit... I'll close it for now!

**Comment by Scrumplex** [comment]
I don't think it needs many changes. You could just make your new options exclusive to the quit option in #341.

**Comment by flowln** [comment]
> I don't think it needs many changes. You could just make your new options exclusive to the quit option in #341.

Indeed that could work. However, I want to make this in a clean way. This could possibly involve having, when the `QuitAfterGameStop` option is set, activating an option like "Open game only in case of a crash" or something. As the way it is on this PR, there's two options (`CloseAfterGameStop` and `OpenOnGameExit`) that do basically the same, just in a confusing way :P

Of course, I will not throw away the work done here, but I'll move it to another PR once I figure the details exactly, and to keep the commit history a little bit cleaner :)

**Comment by d-513** [comment]
Sorry!

**Pull request closed without merging**
