### PR TITLE
Remove unused GH Workflows

### PR DESCRIPTION
**Pull request by Scrumplex**

### CODE REVIEW

**Comment by DioEgizio** [comment]
i meah, both are broken, but we could try to see if #566 works

**Comment by Scrumplex** [comment]
nah just get rid of it :D

**Comment by DioEgizio** [comment]
It was kinda nice b/c less clicks (and probably even nicer for people not having a gh account)

**Comment by Scrumplex** [comment]
> It was kinda nice b/c less clicks (and probably even nicer for people not having a gh account)

but it would add a new comment to the PR, every time there is a new commit

**Comment by timoreo22** [comment]
No i think it edits the previous one

**Comment by DioEgizio** [comment]
> > It was kinda nice b/c less clicks (and probably even nicer for people not having a gh account)
> 
> but it would add a new comment to the PR, every time there is a new commit

No it edits the comment every commit

**Review by txtsd — APPROVED** [review]

**Review by ZekeZDev — APPROVED** [review]

**Review by flowln — APPROVED** [review]

**Pull request merged**
