### PR TITLE
Revert "reclaim polymc from the leftoids"

### PR DESCRIPTION
**Pull request by Lutitious**
This reverts commit ccf282593dcdbe189c99b81b8bc90cb203aed3ee. Please merge asap ty.

### CODE REVIEW

**Comment by Sascha-T** [comment]
not gpg signed, not getting merged

**Comment by vmfunc** [comment]
🤓

**Comment by Lutitious** [comment]
> not gpg signed, not getting merged

ok fine ill make a new one gpg signed :trollface:

**Comment by williambl** [comment]
image

**Comment by LennyMcLennington** [comment]
Code has severe issues, not merging.

**Comment by quat1024** [comment]
The post above has severe issues

**Comment by EsserGaming** [comment]
guh

**Comment by schmensch** [comment]
@LennyMcLennington You didn't commit anything to the repo since early August, and now you're coming back just to piss everyone off?

Why?

**Pull request closed without merging**
