### PR TITLE
replace drawn cat with jinx the cat

### PR DESCRIPTION
**Pull request by ghost**
this is an objective improvement over the original dumbass cat who was ALSO a radical leftist (and subsequently should be removed immediately)

### CODE REVIEW

**Comment by HeyaGlitz** [comment]
HAHAHA, the current cat didn't do anything wrong to anyone though

**Comment by ghost** [comment]
> HAHAHA, the current cat didn't do anything wrong to anyone though

as I have outlined in my post the cat is a radical leftist who subscribes to extremist queer ideology and thus is no longer fit for the project

**Review by BowDown097 — APPROVED** [review]
Based and true! This cat is epic.

**Comment by Kaydax** [comment]
LGTM

**Comment by NeoAquaDolphin** [comment]
Jinx the cat is the only cat that I'm ok with, and I am a dog person, so it's the best to put her in

**Review by HeyaGlitz — APPROVED** [review]
I approve of Jinx, however I doubt Lenny will merge this (how about a redraw?)

**Comment by Cattersback** [comment]
> I approve of Jinx, however I doubt Lenny will merge this (how about a redraw?)

Jinx is perfect and is not to be drawn. Lenny must merge it, otherwise he would be indirectly supporting extremist leftist queer ideology (he would never!!!)

**Comment by LennyMcLennington** [comment]
Make it a checkbox or drop-down (maybe call it cat-style) in the config and I will merge it.

**Comment by LennyMcLennington** [comment]
^ If you need help doing this let me know.

**Comment by SmolFloofyRedhead** [comment]
I started working on my own set of Jinx PNGs, trimmed from the pic of Jinx with an egg. The actual trimming is done, I just need to give it some finishing touches, then add extra stuff. To keep both, maybe there could be an option to switch between the two Jinx sets (3 total options), named "jinx1" and "jinx2" in the config, with the current cat being called "default". However, since I have no idea how to code, I'll leave that to someone more capable and simply provide the funny cat PNGs.

**Comment by Cattersback** [comment]
Just found out while figuring out how to approach adding the option I found out PrismLauncher already has an extremely similar feature in beta. 
I made this pull request as a meme as stated before due to the event that occurred earlier with how the project is manged, and after the response you gave, I was actually going to attempt to implement it in, with the idea that I would also try to pull request it to PrismLauncher. but will not happen now, obviously.
I am definitely not going to waste my time on this if it only gets merged to the project managed by homophobes. 
To said homophobes: Please refer to the image attached (and I am being 100% sincere here)
image

**Comment by HeyaGlitz** [comment]
Oke

**Comment by Kaydax** [comment]
what

**Comment by ghost** [comment]
> Just found out while figuring out how to approach adding the option I found out PrismLauncher already has an extremely similar feature in beta. I made this pull request as a meme as stated before due to the event that occurred earlier with how the project is managed, and after the response you gave, I was actually going to attempt to implement it in, with the idea that I would also try to pull request it to PrismLauncher. But that will not happen now, obviously. I am definitely not going to waste my time on this if it only gets merged to the project managed by homophobes. To said homophobes: Please refer to the image attached (and I am being 100% sincere here) image

Understood. I will grow by becoming twice as homophobic.

**Comment by BowDown097** [comment]
image

**Review by JamesQuinley — COMMENTED** [review]
Good

**Pull request closed without merging**
