### PR TITLE
Customizability of the toolbar

### PR DESCRIPTION
**Pull request by ryanccn**
Signed-off-by: Ryan Cao <70191398+ryanccn@users.noreply.github.com>

### CODE REVIEW

**Comment by ryanccn** [comment]
Can anyone check this out? It works for me currently.

The CSV editing interface could use some improvement, but it would be a bit more difficult.

**Comment by ryanccn** [comment]
I made the UX better

**Comment by flowln** [comment]
I feel like this would be better off in a standalone dialog, accessible through the right-click menu on the toolbar, rather than in the settings. Right now, they are disconnected from each other, which isn't very good for UX IMO.

**Comment by ryanccn** [comment]
🤔

**Comment by ZekeZDev** [comment]
I think its fine to be in settings for now but once I get time to work on the theming and customisation page I think it will make sense to have it there.

**Comment by flowln** [comment]
> I think its fine to be in settings for now but once I get time to work on the theming and customisation page I think it will make sense to have it there.

Even like that, I still think that having this separated from the actual thing that's being updated isn't good from a user experience point. I'd rather have customization of specific things in the launcher be done next to those same things, while global options, like themes, icons, fonts, etc, could be done in a separate page for customization in the global options.

**Comment by DioEgizio** [comment]
dead pr?

**Comment by ryanccn** [comment]
should I add the toolbar context menu button thingy thingy or not

> I don't want to

**Comment by ryanccn** [comment]
> I think its fine to be in settings for now but once I get time to work on the theming and customisation page I think it will make sense to have it there.

this

**Pull request closed without merging**
