### PR TITLE
Backport for 1.1.1

### PR DESCRIPTION
**Pull request by Scrumplex**

### CODE REVIEW

**Comment by DioEgizio** [comment]
we definitely need the msys2 pr too

**Comment by Scrumplex** [comment]
I need to figure out if this is the right way to do this anyway

**Comment by Scrumplex** [comment]
I feel like this is going to make our commit history ugly.

**Comment by DioEgizio** [comment]
> I feel like this is going to make our commit history ugly.

yeah that's the issue

**Comment by DioEgizio** [comment]
https://github.com/PolyMC/PolyMC/actions/runs/2012181030 you should probably re-run the job, the adoptium api had some issues i guess

**Comment by DioEgizio** [comment]
Wouldn't it make sense to add the #292 patches here?
Also the gpl-3-only patches

**Comment by Scrumplex** [comment]
Good point. Gonna deal with it later

**Comment by Scrumplex** [comment]
These should be all changes

**Comment by Scrumplex** [comment]
(Apart from version bump)

**Comment by LennyMcLennington** [comment]
What's the purpose of this

**Comment by LennyMcLennington** [comment]
Wait so if I understand right there's some new features in develop and we only want to include the bug fixes for 1.1.1 so we need to do this

**Comment by Scrumplex** [comment]
Yes

**Review by ZekeZDev — APPROVED** [review]

**Review by txtsd — APPROVED** [review]

**Review by d-513 — APPROVED** [review]

**Pull request merged**
