### PR TITLE
Increase Mod Downloader's initial size

### LINKED ISSUE #404: Download mod dialog is too small by default
### Operating System

macOS

### Description of bug

The download mod dialog is very short by default, so only one (and a quarter) mod is visible at a time, decreasing usability. This occurs even though the window is quite tall in comparison. The dialog should be taller.

Screen Shot 2022-04-06 at 7 19 30 PM

Additional info: My computer uses a HiDPI display. I tested this in a Debian 11 (GNOME) VM without HiDPI enabled, and it was not as bad (not sure if HiDPI has anything to do with it though).

Screen Shot 2022-04-06 at 7 26 07 PM

This is probably low priority, as the user can resize the dialog manually to make it bigger to workaround the issue.

### Steps to reproduce

1. Open PolyMC
2. Select an instance
3. Edit the instance
4. Press the "Mods" tab
5. Press the "Download mods" button

### Suspected cause

https://github.com/PolyMC/PolyMC/blob/5b8003cbe502af04792f4c462b1b8094444e19ad/launcher/ui/dialogs/ModDownloadDialog.cpp#L25

Is a hardcoded size necessary, or will Qt choose an appropriate size automatically?

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### PR DESCRIPTION
**Pull request by txtsd**
This sets its width and height to 50% screen width and height.

Not sure if this is the best way to do it though. Suggestions welcome!

Closes #404 

EDIT: Looks like this

### CODE REVIEW

**Comment by Scrumplex** [comment]
This probably isn't the best way of doing this. The window would be too wide on an ultrawide.

**Comment by txtsd** [comment]
That's true. And setting a manual size might not work properly on high DPI screens.

**Review by kthchew — CHANGES_REQUESTED** [review]
Maybe you could use a `sizeHint` with appropriate size policies for the vertical/horizontal directions instead?

**Comment by txtsd** [comment]
Closing in favor of #392

**Pull request closed without merging**
