### PR TITLE
Suggestion: Drop quilt support

### PR DESCRIPTION
**Pull request by Kaydax**
Quilt support is not necessary, as it's basically just a straight fabric fork with minor changes. There is not a large enough userbase to warrant keeping support for the loader itself, and there are very few, if any, quilt only mods.

Almost all quilt mods work on fabric and vise versa, so keeping support for it is just a waste of time and energy if something breaks.

### CODE REVIEW

**Review by BowDown097 — APPROVED** [review]
Quilt is unnecessary. I don't think anyone will miss it.

**Review by Chrono-byte — APPROVED** [review]
LGTM

**Comment by JamesQuinley** [comment]
Sounds good, waste of time to maintain it regardless.

**Review by JamesQuinley — APPROVED** [review]

**Comment by JamesQuinley** [comment]
To those watching, this PR's goal is to remove redundancy.
Quilt mods will keep working, since they are basically rebranded Fabric mods. 
We also would recommend not making off topic issues, you know who you are.

**Comment by LennyMcLennington** [comment]
This is never going to happen unless Quilt becomes irreparably broken and just completely stops working in the launcher.

There is not much point in removing a perfectly working feature from the code base. That said, we might consider changing Quilt to not be used by default, depending on what ends up happening with the Felt project which could be used alongside Fabric to run mods that were previously Quilt-only.

**Pull request closed without merging**
