### PR TITLE
Prepare for Nix 2.7

### PR DESCRIPTION
**Pull request by TheOPtimal**
In [Nix 2.7](https://nixos.org/manual/nix/stable/release-notes/rl-2.7.html), the `default*` attributes (e.g. `defaultPackage` and `defaultApp`) have been deprecated in favor of `*.default` attributes (e.g. `packages.default` or `apps.default`).

I've added `*.default` attributes but haven't removed the deprecated `default*` attributes to maintain compatibility with older Nix versions.

### CODE REVIEW

**Comment by Kranzes** [comment]
There is already a PR open for refactoring the flake, #272 , I can cherry-pick this commit to that branch and you can review that PR. I think this change should only be done once NixOS 22.05 is out, because on 21.11 nix 2.3 is still the default.

**Comment by Scrumplex** [comment]
How do we continue with this and #272? I am a Nix noob so I have no idea what you guys are doing :sweat_smile:

**Comment by Kranzes** [comment]
> How do we continue with this and #272? I am a Nix noob so I have no idea what you guys are doing 😅

#272 is ready to be merged already. This PR isn't though since it would break backwards compatibility with the current stable NixOS release. This PR's merge should be delayed until NixOS 21.11 (current release) becomes EOL and replaced by 22.05 which comes out in May.

**Comment by TheOPtimal** [comment]
> > How do we continue with this and #272? I am a Nix noob so I have no idea what you guys are doing 😅
> 
> #272 is ready to be merged already. This PR isn't though since it would break backwards compatibility with the current stable NixOS release. This PR's merge should be delayed until NixOS 21.11 (current release) becomes EOL and replaced by 22.05 which comes out in May.

Actually my PR is backwards compatible.

**Comment by d-513** [comment]
is this still neccesary after #272 merge? can you fix conflicts if yes?

**Comment by Scrumplex** [comment]
The Mojank endpoints we use there will eventually stop working I assume. So this will be needed eventually

**Comment by Scrumplex** [comment]
Oops. Wrong issue 😅

**Comment by txtsd** [comment]
@TheOPtimal 

> is this still neccesary after #272 merge? can you fix conflicts if yes?

**Comment by TheOPtimal** [comment]
> is this still neccesary after #272 merge? can you fix conflicts if yes?

Yes. I'll try to fix conflicts ASAP.

**Comment by TheOPtimal** [comment]
Fixed :)

**Comment by DioEgizio** [comment]
Conflicting again, lol

**Comment by TheOPtimal** [comment]
> Conflicting again, lol

HOOOOOOOOOOOWWWWWWWWWWW

**Comment by DioEgizio** [comment]
yes

**Comment by TheOPtimal** [comment]
resolved again and i swear if you conflicgt this again iiw lilcd ong on nisane

**Review by Scrumplex — APPROVED** [review]

**Review by Scrumplex — APPROVED** [review]
Whoever merges this, please squash

**Comment by TheOPtimal** [comment]
Merge quick, because Nix 2.9 is already out and we're **very** late

**Review by flowln — APPROVED** [review]

**Review by d-513 — APPROVED** [review]

**Pull request merged**
