### PR TITLE
Nix Support

### PR DESCRIPTION
**Pull request by cidkidnix**
NixOS support for polymc packages

### CODE REVIEW

**Comment by ghost** [comment]
you should probably put this in `packages/nix`.

**Comment by cidkidnix** [comment]
I can move the `nix` folder into there but the flake.nix at the very least has to be in the root of the repo

**Comment by ghost** [comment]
Additionally you don't need to make the desktop file, it should install automatically with lin-system

**Comment by cidkidnix** [comment]
the generated desktop file doesn't launch at all for me

EDIT: probably due to the fact that we have to wrap the executable

**Comment by ghost** [comment]
Oh, I see. Then you can move the nix dir to the packages dir

**Comment by cidkidnix** [comment]
that should fix pretty much everything

**Pull request merged**
