### PR TITLE
Allow components to specify Java agents and JVM arguments

### PR DESCRIPTION
**Pull request by exaskye**
Java agents provide a well-supported generic facility for modding any version and adding pre-launch hooks, such as for a universal updater, which was discussed when I brought this up at upstream: https://tinyurl.com/2p8rcvsf (URL shortened to avoid linking the issue to this PR)

I'm not very good at C++ dev, please let me know if anything here doesn't make sense. I also added a warning to [CustomCommands.ui](https://github.com/PolyMC/PolyMC/compare/develop...unascribed:feature/java-agents?expand=1#diff-73ff26cff09dd28a4590c26e9f185c35a23b2858bd423a3083bfa6a37049278f) about spaces causing the `INST_JAVA_ARGS` env var to break, as I was looking at that code and noticed the issue:
image

JSON component I used to test this in a Beta 1.7.3 instance (add an empty jar mod to bypass the security exception):
```json
{
    "formatVersion": 1,
    "name": "Ears",
    "uid": "com.unascribed.ears",
    "version": "1.4.5",
    "+agents": [
        {
            "name": "com.unascribed.ears:ears-bta:1.4.5",
            "MMC-absoluteUrl": "https://git.sleeping.town/attachments/f4067779-d433-439c-a0cc-01c3114839a7"
        }
    ],
    "+jvmArgs": [
        "-DpolyMc.Hello=true"
    ]
}

```

### CODE REVIEW

**Comment by Scrumplex** [comment]
I think feature freeze for 1.1.0 will never start :D

**Comment by exaskye** [comment]
re: labels, I tested this on Linux as part of making the PR.

> I think feature freeze for 1.1.0 will never start :D

Oops.

**Comment by LennyMcLennington** [comment]
> I think feature freeze for 1.1.0 will never start :D

Does this need to be in 1.1.0?

**Comment by Scrumplex** [comment]
> Does this need to be in 1.1.0?

Not necessarily but it doesn't look like a large feature that needs extensive testing, especially as it's basically only reserved for use by advanced users

**Comment by Scrumplex** [comment]
do we need to delete `META-INF`? Is it 2011 again?

**Comment by exaskye** [comment]
Force-pushed as I've decided after further consideration it is best not to use any specific project name for extension prefixes. Following upstream's lead of just using "+".

> do we need to delete META-INF? Is it 2011 again?

The only reason the Ears agent causes a security exception with META-INF present is it has to define classes in the root package; not all Java agents will need META-INF removed. My original motivation for adding Java agent support was for an updater — distributing that updater with upstream requires clobbering the user's JVM argument settings. Such an updater doesn't define new classes in existing packages and therefore doesn't cause the error.

**Comment by Scrumplex** [comment]
We might not get this reviewed until 1.1.0. I am going to postpone this 1.2.0 for now.

**Comment by ZekeZDev** [comment]
Can we get this in 1.1.1 @Scrumplex ?

**Comment by Scrumplex** [comment]
> Can we get this in 1.1.0 @Scrumplex ?

Nope. As per semantic versioning this belongs into a new feature release.

**Review by Scrumplex — APPROVED** [review]

**Comment by DioEgizio** [comment]
merge of this wen

**Comment by Scrumplex** [comment]
This is conflicting with develop

**Review by ZekeZDev — APPROVED** [review]

**Review by txtsd — APPROVED** [review]

**Comment by DioEgizio** [comment]
This is conflicting with develop again

**Comment by Scrumplex** [comment]
@unascribed Do you mind if I squash the commits? Or do you want to do it yourself (and keep your own signature instead of GitHub's signature)

**Comment by exaskye** [comment]
I've already been doing the merges in GitHub Web, so it doesn't matter.

**Comment by Scrumplex** [comment]
Thanks!

**Pull request merged**
