### PR TITLE
feat(actions): add codeql code scanning

### PR DESCRIPTION
**Pull request by DioEgizio**
This pr adds code scanning with codeql, to replace the old LGTM.com which is gonna die later this year.

### CODE REVIEW

**Comment by ryanccn** [comment]
LGTM.com doesn't LGTM

**Comment by DioEgizio** [comment]
https://github.blog/2022-08-15-the-next-step-for-lgtm-com-github-code-scanning/

**Review by Scrumplex — APPROVED** [review]

**Comment by TayouVR** [comment]
> For those repositories, we will create pull requests that add a [GitHub Actions workflow that runs code scanning](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/setting-up-code-scanning-for-a-repository#setting-up-code-scanning-manually)

won't github already make a PR for this themselves?

**Comment by DioEgizio** [comment]
> > For those repositories, we will create pull requests that add a [GitHub Actions workflow that runs code scanning](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/setting-up-code-scanning-for-a-repository#setting-up-code-scanning-manually)
> 
> won't github already make a PR for this themselves?

I don't know but I did it myself anyways

**Review by flowln — APPROVED** [review]

**Pull request merged**
