### PR TITLE
fix(COPYING): fix COPYING.md by adding some missing copyright notices

### PR DESCRIPTION
**Pull request by DioEgizio**
this pr adds a few copyright notices to COPYING.MD, including:
- feral's gamemode
- mingw-w64

### CODE REVIEW

**Review by Scrumplex — APPROVED** [review]

**Comment by Scrumplex** [comment]
:trollface:

**Review by Scrumplex — CHANGES_REQUESTED** [review]
:trollface:

**Review by Scrumplex — APPROVED** [review]

**Review by flowln — APPROVED** [review]
:trollface:

**Comment by DioEgizio** [comment]
2 approvals 👀

**Comment by flowln** [comment]
oh yea i forgor we only need two now :skull:

**Comment by DioEgizio** [comment]
You forgor 💀

**Comment by BeansBeefBroccoli** [comment]
You forgor 💀

I hate autocorrect

**Pull request merged**
